
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model StoreSetting
 * 
 */
export type StoreSetting = Prisma.StoreSettingModel
/**
 * Model LinkGroup
 * 
 */
export type LinkGroup = Prisma.LinkGroupModel
/**
 * Model NavLink
 * 
 */
export type NavLink = Prisma.NavLinkModel
/**
 * Model ContactSubmission
 * 
 */
export type ContactSubmission = Prisma.ContactSubmissionModel
/**
 * Model PageContent
 * 
 */
export type PageContent = Prisma.PageContentModel
/**
 * Model NewsletterSubscriber
 * 
 */
export type NewsletterSubscriber = Prisma.NewsletterSubscriberModel
/**
 * Model HeroBanner
 * 
 */
export type HeroBanner = Prisma.HeroBannerModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model ProductImage
 * 
 */
export type ProductImage = Prisma.ProductImageModel
/**
 * Model Review
 * 
 */
export type Review = Prisma.ReviewModel
/**
 * Model Service
 * 
 */
export type Service = Prisma.ServiceModel
/**
 * Model PromoBanner
 * 
 */
export type PromoBanner = Prisma.PromoBannerModel
/**
 * Model TrendingPromo
 * 
 */
export type TrendingPromo = Prisma.TrendingPromoModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model DiscountItem
 * 
 */
export type DiscountItem = Prisma.DiscountItemModel
/**
 * Model Brand
 * 
 */
export type Brand = Prisma.BrandModel
/**
 * Model Newsletter
 * 
 */
export type Newsletter = Prisma.NewsletterModel
/**
 * Model BlogPost
 * 
 */
export type BlogPost = Prisma.BlogPostModel
