
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model StoreSetting
 * 
 */
export type StoreSetting = Prisma.StoreSettingModel
/**
 * Model LinkGroup
 * 
 */
export type LinkGroup = Prisma.LinkGroupModel
/**
 * Model NavLink
 * 
 */
export type NavLink = Prisma.NavLinkModel
/**
 * Model ContactSubmission
 * 
 */
export type ContactSubmission = Prisma.ContactSubmissionModel
/**
 * Model PageContent
 * 
 */
export type PageContent = Prisma.PageContentModel
/**
 * Model NewsletterSubscriber
 * 
 */
export type NewsletterSubscriber = Prisma.NewsletterSubscriberModel
/**
 * Model HeroBanner
 * 
 */
export type HeroBanner = Prisma.HeroBannerModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model Service
 * 
 */
export type Service = Prisma.ServiceModel
/**
 * Model PromoBanner
 * 
 */
export type PromoBanner = Prisma.PromoBannerModel
