
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  USER: 'USER',
  ADMIN: 'ADMIN'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const LinkSection = {
  HEADER_MAIN: 'HEADER_MAIN',
  FOOTER: 'FOOTER'
} as const

export type LinkSection = (typeof LinkSection)[keyof typeof LinkSection]


export const OrderStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]


export const EmailType = {
  ORDER_CONFIRMATION: 'ORDER_CONFIRMATION',
  ORDER_STATUS_UPDATE: 'ORDER_STATUS_UPDATE',
  SHIPPING_NOTIFICATION: 'SHIPPING_NOTIFICATION',
  DELIVERY_CONFIRMATION: 'DELIVERY_CONFIRMATION',
  MARKETING: 'MARKETING',
  PASSWORD_RESET: 'PASSWORD_RESET'
} as const

export type EmailType = (typeof EmailType)[keyof typeof EmailType]


export const EmailStatus = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  BOUNCED: 'BOUNCED'
} as const

export type EmailStatus = (typeof EmailStatus)[keyof typeof EmailStatus]


export const StockMovementType = {
  SALE: 'SALE',
  RESTOCK: 'RESTOCK',
  ADJUSTMENT: 'ADJUSTMENT',
  RETURN: 'RETURN',
  DAMAGE: 'DAMAGE',
  TRANSFER: 'TRANSFER'
} as const

export type StockMovementType = (typeof StockMovementType)[keyof typeof StockMovementType]
