import type { Metadata } from "next";
import { Josefin_Sans, Lato } from "next/font/google";
import HeaderContainer from "@/components/header/HeaderContainer";
import FooterContainer from "@/components/footer/FooterContainer";
import "./globals.css";

const josefin = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-josefin', // Define the variable name
});

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'], // Lato requires specific weights
  display: 'swap',
  variable: '--font-lato', // Define the variable name
});

export const metadata: Metadata = {
  title: "Water Medics Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
      <body
        className={`${josefin.variable} ${lato.variable} antialiased`}
      >
        <HeaderContainer />
        {children}
        <FooterContainer />
      </body>
    </html>
  );
}

