
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DiscountItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DiscountItem
 * 
 */
export type DiscountItemModel = runtime.Types.Result.DefaultSelection<Prisma.$DiscountItemPayload>

export type AggregateDiscountItem = {
  _count: DiscountItemCountAggregateOutputType | null
  _min: DiscountItemMinAggregateOutputType | null
  _max: DiscountItemMaxAggregateOutputType | null
}

export type DiscountItemMinAggregateOutputType = {
  id: string | null
  title: string | null
  subtitle: string | null
  description: string | null
  buttonText: string | null
  categoryId: string | null
  productId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DiscountItemMaxAggregateOutputType = {
  id: string | null
  title: string | null
  subtitle: string | null
  description: string | null
  buttonText: string | null
  categoryId: string | null
  productId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DiscountItemCountAggregateOutputType = {
  id: number
  title: number
  subtitle: number
  description: number
  features: number
  buttonText: number
  categoryId: number
  productId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DiscountItemMinAggregateInputType = {
  id?: true
  title?: true
  subtitle?: true
  description?: true
  buttonText?: true
  categoryId?: true
  productId?: true
  createdAt?: true
  updatedAt?: true
}

export type DiscountItemMaxAggregateInputType = {
  id?: true
  title?: true
  subtitle?: true
  description?: true
  buttonText?: true
  categoryId?: true
  productId?: true
  createdAt?: true
  updatedAt?: true
}

export type DiscountItemCountAggregateInputType = {
  id?: true
  title?: true
  subtitle?: true
  description?: true
  features?: true
  buttonText?: true
  categoryId?: true
  productId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DiscountItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DiscountItem to aggregate.
   */
  where?: Prisma.DiscountItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DiscountItems to fetch.
   */
  orderBy?: Prisma.DiscountItemOrderByWithRelationInput | Prisma.DiscountItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DiscountItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DiscountItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DiscountItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DiscountItems
  **/
  _count?: true | DiscountItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DiscountItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DiscountItemMaxAggregateInputType
}

export type GetDiscountItemAggregateType<T extends DiscountItemAggregateArgs> = {
      [P in keyof T & keyof AggregateDiscountItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDiscountItem[P]>
    : Prisma.GetScalarType<T[P], AggregateDiscountItem[P]>
}




export type DiscountItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DiscountItemWhereInput
  orderBy?: Prisma.DiscountItemOrderByWithAggregationInput | Prisma.DiscountItemOrderByWithAggregationInput[]
  by: Prisma.DiscountItemScalarFieldEnum[] | Prisma.DiscountItemScalarFieldEnum
  having?: Prisma.DiscountItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DiscountItemCountAggregateInputType | true
  _min?: DiscountItemMinAggregateInputType
  _max?: DiscountItemMaxAggregateInputType
}

export type DiscountItemGroupByOutputType = {
  id: string
  title: string
  subtitle: string
  description: string
  features: string[]
  buttonText: string
  categoryId: string
  productId: string
  createdAt: Date
  updatedAt: Date
  _count: DiscountItemCountAggregateOutputType | null
  _min: DiscountItemMinAggregateOutputType | null
  _max: DiscountItemMaxAggregateOutputType | null
}

type GetDiscountItemGroupByPayload<T extends DiscountItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DiscountItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DiscountItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DiscountItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DiscountItemGroupByOutputType[P]>
      }
    >
  >



export type DiscountItemWhereInput = {
  AND?: Prisma.DiscountItemWhereInput | Prisma.DiscountItemWhereInput[]
  OR?: Prisma.DiscountItemWhereInput[]
  NOT?: Prisma.DiscountItemWhereInput | Prisma.DiscountItemWhereInput[]
  id?: Prisma.StringFilter<"DiscountItem"> | string
  title?: Prisma.StringFilter<"DiscountItem"> | string
  subtitle?: Prisma.StringFilter<"DiscountItem"> | string
  description?: Prisma.StringFilter<"DiscountItem"> | string
  features?: Prisma.StringNullableListFilter<"DiscountItem">
  buttonText?: Prisma.StringFilter<"DiscountItem"> | string
  categoryId?: Prisma.StringFilter<"DiscountItem"> | string
  productId?: Prisma.StringFilter<"DiscountItem"> | string
  createdAt?: Prisma.DateTimeFilter<"DiscountItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DiscountItem"> | Date | string
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type DiscountItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  subtitle?: Prisma.SortOrder
  description?: Prisma.SortOrder
  features?: Prisma.SortOrder
  buttonText?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  category?: Prisma.CategoryOrderByWithRelationInput
  product?: Prisma.ProductOrderByWithRelationInput
}

export type DiscountItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  categoryId?: string
  AND?: Prisma.DiscountItemWhereInput | Prisma.DiscountItemWhereInput[]
  OR?: Prisma.DiscountItemWhereInput[]
  NOT?: Prisma.DiscountItemWhereInput | Prisma.DiscountItemWhereInput[]
  title?: Prisma.StringFilter<"DiscountItem"> | string
  subtitle?: Prisma.StringFilter<"DiscountItem"> | string
  description?: Prisma.StringFilter<"DiscountItem"> | string
  features?: Prisma.StringNullableListFilter<"DiscountItem">
  buttonText?: Prisma.StringFilter<"DiscountItem"> | string
  productId?: Prisma.StringFilter<"DiscountItem"> | string
  createdAt?: Prisma.DateTimeFilter<"DiscountItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DiscountItem"> | Date | string
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id" | "categoryId">

export type DiscountItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  subtitle?: Prisma.SortOrder
  description?: Prisma.SortOrder
  features?: Prisma.SortOrder
  buttonText?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DiscountItemCountOrderByAggregateInput
  _max?: Prisma.DiscountItemMaxOrderByAggregateInput
  _min?: Prisma.DiscountItemMinOrderByAggregateInput
}

export type DiscountItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.DiscountItemScalarWhereWithAggregatesInput | Prisma.DiscountItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.DiscountItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DiscountItemScalarWhereWithAggregatesInput | Prisma.DiscountItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DiscountItem"> | string
  title?: Prisma.StringWithAggregatesFilter<"DiscountItem"> | string
  subtitle?: Prisma.StringWithAggregatesFilter<"DiscountItem"> | string
  description?: Prisma.StringWithAggregatesFilter<"DiscountItem"> | string
  features?: Prisma.StringNullableListFilter<"DiscountItem">
  buttonText?: Prisma.StringWithAggregatesFilter<"DiscountItem"> | string
  categoryId?: Prisma.StringWithAggregatesFilter<"DiscountItem"> | string
  productId?: Prisma.StringWithAggregatesFilter<"DiscountItem"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DiscountItem"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DiscountItem"> | Date | string
}

export type DiscountItemCreateInput = {
  id?: string
  title: string
  subtitle: string
  description: string
  features?: Prisma.DiscountItemCreatefeaturesInput | string[]
  buttonText?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  category: Prisma.CategoryCreateNestedOneWithoutDiscountItemInput
  product: Prisma.ProductCreateNestedOneWithoutDiscountItemsInput
}

export type DiscountItemUncheckedCreateInput = {
  id?: string
  title: string
  subtitle: string
  description: string
  features?: Prisma.DiscountItemCreatefeaturesInput | string[]
  buttonText?: string
  categoryId: string
  productId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DiscountItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subtitle?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.DiscountItemUpdatefeaturesInput | string[]
  buttonText?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneRequiredWithoutDiscountItemNestedInput
  product?: Prisma.ProductUpdateOneRequiredWithoutDiscountItemsNestedInput
}

export type DiscountItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subtitle?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.DiscountItemUpdatefeaturesInput | string[]
  buttonText?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DiscountItemCreateManyInput = {
  id?: string
  title: string
  subtitle: string
  description: string
  features?: Prisma.DiscountItemCreatefeaturesInput | string[]
  buttonText?: string
  categoryId: string
  productId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DiscountItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subtitle?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.DiscountItemUpdatefeaturesInput | string[]
  buttonText?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DiscountItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subtitle?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.DiscountItemUpdatefeaturesInput | string[]
  buttonText?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DiscountItemListRelationFilter = {
  every?: Prisma.DiscountItemWhereInput
  some?: Prisma.DiscountItemWhereInput
  none?: Prisma.DiscountItemWhereInput
}

export type DiscountItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DiscountItemNullableScalarRelationFilter = {
  is?: Prisma.DiscountItemWhereInput | null
  isNot?: Prisma.DiscountItemWhereInput | null
}

export type DiscountItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  subtitle?: Prisma.SortOrder
  description?: Prisma.SortOrder
  features?: Prisma.SortOrder
  buttonText?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DiscountItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  subtitle?: Prisma.SortOrder
  description?: Prisma.SortOrder
  buttonText?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DiscountItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  subtitle?: Prisma.SortOrder
  description?: Prisma.SortOrder
  buttonText?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DiscountItemCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.DiscountItemCreateWithoutProductInput, Prisma.DiscountItemUncheckedCreateWithoutProductInput> | Prisma.DiscountItemCreateWithoutProductInput[] | Prisma.DiscountItemUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.DiscountItemCreateOrConnectWithoutProductInput | Prisma.DiscountItemCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.DiscountItemCreateManyProductInputEnvelope
  connect?: Prisma.DiscountItemWhereUniqueInput | Prisma.DiscountItemWhereUniqueInput[]
}

export type DiscountItemUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.DiscountItemCreateWithoutProductInput, Prisma.DiscountItemUncheckedCreateWithoutProductInput> | Prisma.DiscountItemCreateWithoutProductInput[] | Prisma.DiscountItemUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.DiscountItemCreateOrConnectWithoutProductInput | Prisma.DiscountItemCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.DiscountItemCreateManyProductInputEnvelope
  connect?: Prisma.DiscountItemWhereUniqueInput | Prisma.DiscountItemWhereUniqueInput[]
}

export type DiscountItemUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.DiscountItemCreateWithoutProductInput, Prisma.DiscountItemUncheckedCreateWithoutProductInput> | Prisma.DiscountItemCreateWithoutProductInput[] | Prisma.DiscountItemUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.DiscountItemCreateOrConnectWithoutProductInput | Prisma.DiscountItemCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.DiscountItemUpsertWithWhereUniqueWithoutProductInput | Prisma.DiscountItemUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.DiscountItemCreateManyProductInputEnvelope
  set?: Prisma.DiscountItemWhereUniqueInput | Prisma.DiscountItemWhereUniqueInput[]
  disconnect?: Prisma.DiscountItemWhereUniqueInput | Prisma.DiscountItemWhereUniqueInput[]
  delete?: Prisma.DiscountItemWhereUniqueInput | Prisma.DiscountItemWhereUniqueInput[]
  connect?: Prisma.DiscountItemWhereUniqueInput | Prisma.DiscountItemWhereUniqueInput[]
  update?: Prisma.DiscountItemUpdateWithWhereUniqueWithoutProductInput | Prisma.DiscountItemUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.DiscountItemUpdateManyWithWhereWithoutProductInput | Prisma.DiscountItemUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.DiscountItemScalarWhereInput | Prisma.DiscountItemScalarWhereInput[]
}

export type DiscountItemUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.DiscountItemCreateWithoutProductInput, Prisma.DiscountItemUncheckedCreateWithoutProductInput> | Prisma.DiscountItemCreateWithoutProductInput[] | Prisma.DiscountItemUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.DiscountItemCreateOrConnectWithoutProductInput | Prisma.DiscountItemCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.DiscountItemUpsertWithWhereUniqueWithoutProductInput | Prisma.DiscountItemUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.DiscountItemCreateManyProductInputEnvelope
  set?: Prisma.DiscountItemWhereUniqueInput | Prisma.DiscountItemWhereUniqueInput[]
  disconnect?: Prisma.DiscountItemWhereUniqueInput | Prisma.DiscountItemWhereUniqueInput[]
  delete?: Prisma.DiscountItemWhereUniqueInput | Prisma.DiscountItemWhereUniqueInput[]
  connect?: Prisma.DiscountItemWhereUniqueInput | Prisma.DiscountItemWhereUniqueInput[]
  update?: Prisma.DiscountItemUpdateWithWhereUniqueWithoutProductInput | Prisma.DiscountItemUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.DiscountItemUpdateManyWithWhereWithoutProductInput | Prisma.DiscountItemUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.DiscountItemScalarWhereInput | Prisma.DiscountItemScalarWhereInput[]
}

export type DiscountItemCreateNestedOneWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.DiscountItemCreateWithoutCategoryInput, Prisma.DiscountItemUncheckedCreateWithoutCategoryInput>
  connectOrCreate?: Prisma.DiscountItemCreateOrConnectWithoutCategoryInput
  connect?: Prisma.DiscountItemWhereUniqueInput
}

export type DiscountItemUncheckedCreateNestedOneWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.DiscountItemCreateWithoutCategoryInput, Prisma.DiscountItemUncheckedCreateWithoutCategoryInput>
  connectOrCreate?: Prisma.DiscountItemCreateOrConnectWithoutCategoryInput
  connect?: Prisma.DiscountItemWhereUniqueInput
}

export type DiscountItemUpdateOneWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.DiscountItemCreateWithoutCategoryInput, Prisma.DiscountItemUncheckedCreateWithoutCategoryInput>
  connectOrCreate?: Prisma.DiscountItemCreateOrConnectWithoutCategoryInput
  upsert?: Prisma.DiscountItemUpsertWithoutCategoryInput
  disconnect?: Prisma.DiscountItemWhereInput | boolean
  delete?: Prisma.DiscountItemWhereInput | boolean
  connect?: Prisma.DiscountItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DiscountItemUpdateToOneWithWhereWithoutCategoryInput, Prisma.DiscountItemUpdateWithoutCategoryInput>, Prisma.DiscountItemUncheckedUpdateWithoutCategoryInput>
}

export type DiscountItemUncheckedUpdateOneWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.DiscountItemCreateWithoutCategoryInput, Prisma.DiscountItemUncheckedCreateWithoutCategoryInput>
  connectOrCreate?: Prisma.DiscountItemCreateOrConnectWithoutCategoryInput
  upsert?: Prisma.DiscountItemUpsertWithoutCategoryInput
  disconnect?: Prisma.DiscountItemWhereInput | boolean
  delete?: Prisma.DiscountItemWhereInput | boolean
  connect?: Prisma.DiscountItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DiscountItemUpdateToOneWithWhereWithoutCategoryInput, Prisma.DiscountItemUpdateWithoutCategoryInput>, Prisma.DiscountItemUncheckedUpdateWithoutCategoryInput>
}

export type DiscountItemCreatefeaturesInput = {
  set: string[]
}

export type DiscountItemUpdatefeaturesInput = {
  set?: string[]
  push?: string | string[]
}

export type DiscountItemCreateWithoutProductInput = {
  id?: string
  title: string
  subtitle: string
  description: string
  features?: Prisma.DiscountItemCreatefeaturesInput | string[]
  buttonText?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  category: Prisma.CategoryCreateNestedOneWithoutDiscountItemInput
}

export type DiscountItemUncheckedCreateWithoutProductInput = {
  id?: string
  title: string
  subtitle: string
  description: string
  features?: Prisma.DiscountItemCreatefeaturesInput | string[]
  buttonText?: string
  categoryId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DiscountItemCreateOrConnectWithoutProductInput = {
  where: Prisma.DiscountItemWhereUniqueInput
  create: Prisma.XOR<Prisma.DiscountItemCreateWithoutProductInput, Prisma.DiscountItemUncheckedCreateWithoutProductInput>
}

export type DiscountItemCreateManyProductInputEnvelope = {
  data: Prisma.DiscountItemCreateManyProductInput | Prisma.DiscountItemCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type DiscountItemUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.DiscountItemWhereUniqueInput
  update: Prisma.XOR<Prisma.DiscountItemUpdateWithoutProductInput, Prisma.DiscountItemUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.DiscountItemCreateWithoutProductInput, Prisma.DiscountItemUncheckedCreateWithoutProductInput>
}

export type DiscountItemUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.DiscountItemWhereUniqueInput
  data: Prisma.XOR<Prisma.DiscountItemUpdateWithoutProductInput, Prisma.DiscountItemUncheckedUpdateWithoutProductInput>
}

export type DiscountItemUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.DiscountItemScalarWhereInput
  data: Prisma.XOR<Prisma.DiscountItemUpdateManyMutationInput, Prisma.DiscountItemUncheckedUpdateManyWithoutProductInput>
}

export type DiscountItemScalarWhereInput = {
  AND?: Prisma.DiscountItemScalarWhereInput | Prisma.DiscountItemScalarWhereInput[]
  OR?: Prisma.DiscountItemScalarWhereInput[]
  NOT?: Prisma.DiscountItemScalarWhereInput | Prisma.DiscountItemScalarWhereInput[]
  id?: Prisma.StringFilter<"DiscountItem"> | string
  title?: Prisma.StringFilter<"DiscountItem"> | string
  subtitle?: Prisma.StringFilter<"DiscountItem"> | string
  description?: Prisma.StringFilter<"DiscountItem"> | string
  features?: Prisma.StringNullableListFilter<"DiscountItem">
  buttonText?: Prisma.StringFilter<"DiscountItem"> | string
  categoryId?: Prisma.StringFilter<"DiscountItem"> | string
  productId?: Prisma.StringFilter<"DiscountItem"> | string
  createdAt?: Prisma.DateTimeFilter<"DiscountItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DiscountItem"> | Date | string
}

export type DiscountItemCreateWithoutCategoryInput = {
  id?: string
  title: string
  subtitle: string
  description: string
  features?: Prisma.DiscountItemCreatefeaturesInput | string[]
  buttonText?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutDiscountItemsInput
}

export type DiscountItemUncheckedCreateWithoutCategoryInput = {
  id?: string
  title: string
  subtitle: string
  description: string
  features?: Prisma.DiscountItemCreatefeaturesInput | string[]
  buttonText?: string
  productId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DiscountItemCreateOrConnectWithoutCategoryInput = {
  where: Prisma.DiscountItemWhereUniqueInput
  create: Prisma.XOR<Prisma.DiscountItemCreateWithoutCategoryInput, Prisma.DiscountItemUncheckedCreateWithoutCategoryInput>
}

export type DiscountItemUpsertWithoutCategoryInput = {
  update: Prisma.XOR<Prisma.DiscountItemUpdateWithoutCategoryInput, Prisma.DiscountItemUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.DiscountItemCreateWithoutCategoryInput, Prisma.DiscountItemUncheckedCreateWithoutCategoryInput>
  where?: Prisma.DiscountItemWhereInput
}

export type DiscountItemUpdateToOneWithWhereWithoutCategoryInput = {
  where?: Prisma.DiscountItemWhereInput
  data: Prisma.XOR<Prisma.DiscountItemUpdateWithoutCategoryInput, Prisma.DiscountItemUncheckedUpdateWithoutCategoryInput>
}

export type DiscountItemUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subtitle?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.DiscountItemUpdatefeaturesInput | string[]
  buttonText?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutDiscountItemsNestedInput
}

export type DiscountItemUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subtitle?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.DiscountItemUpdatefeaturesInput | string[]
  buttonText?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DiscountItemCreateManyProductInput = {
  id?: string
  title: string
  subtitle: string
  description: string
  features?: Prisma.DiscountItemCreatefeaturesInput | string[]
  buttonText?: string
  categoryId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DiscountItemUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subtitle?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.DiscountItemUpdatefeaturesInput | string[]
  buttonText?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneRequiredWithoutDiscountItemNestedInput
}

export type DiscountItemUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subtitle?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.DiscountItemUpdatefeaturesInput | string[]
  buttonText?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DiscountItemUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  subtitle?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.DiscountItemUpdatefeaturesInput | string[]
  buttonText?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DiscountItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  subtitle?: boolean
  description?: boolean
  features?: boolean
  buttonText?: boolean
  categoryId?: boolean
  productId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["discountItem"]>

export type DiscountItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  subtitle?: boolean
  description?: boolean
  features?: boolean
  buttonText?: boolean
  categoryId?: boolean
  productId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["discountItem"]>

export type DiscountItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  subtitle?: boolean
  description?: boolean
  features?: boolean
  buttonText?: boolean
  categoryId?: boolean
  productId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["discountItem"]>

export type DiscountItemSelectScalar = {
  id?: boolean
  title?: boolean
  subtitle?: boolean
  description?: boolean
  features?: boolean
  buttonText?: boolean
  categoryId?: boolean
  productId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DiscountItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "subtitle" | "description" | "features" | "buttonText" | "categoryId" | "productId" | "createdAt" | "updatedAt", ExtArgs["result"]["discountItem"]>
export type DiscountItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type DiscountItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type DiscountItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $DiscountItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DiscountItem"
  objects: {
    category: Prisma.$CategoryPayload<ExtArgs>
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    subtitle: string
    description: string
    features: string[]
    buttonText: string
    categoryId: string
    productId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["discountItem"]>
  composites: {}
}

export type DiscountItemGetPayload<S extends boolean | null | undefined | DiscountItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DiscountItemPayload, S>

export type DiscountItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DiscountItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DiscountItemCountAggregateInputType | true
  }

export interface DiscountItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DiscountItem'], meta: { name: 'DiscountItem' } }
  /**
   * Find zero or one DiscountItem that matches the filter.
   * @param {DiscountItemFindUniqueArgs} args - Arguments to find a DiscountItem
   * @example
   * // Get one DiscountItem
   * const discountItem = await prisma.discountItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DiscountItemFindUniqueArgs>(args: Prisma.SelectSubset<T, DiscountItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DiscountItemClient<runtime.Types.Result.GetResult<Prisma.$DiscountItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DiscountItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DiscountItemFindUniqueOrThrowArgs} args - Arguments to find a DiscountItem
   * @example
   * // Get one DiscountItem
   * const discountItem = await prisma.discountItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DiscountItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DiscountItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DiscountItemClient<runtime.Types.Result.GetResult<Prisma.$DiscountItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DiscountItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscountItemFindFirstArgs} args - Arguments to find a DiscountItem
   * @example
   * // Get one DiscountItem
   * const discountItem = await prisma.discountItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DiscountItemFindFirstArgs>(args?: Prisma.SelectSubset<T, DiscountItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__DiscountItemClient<runtime.Types.Result.GetResult<Prisma.$DiscountItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DiscountItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscountItemFindFirstOrThrowArgs} args - Arguments to find a DiscountItem
   * @example
   * // Get one DiscountItem
   * const discountItem = await prisma.discountItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DiscountItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DiscountItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DiscountItemClient<runtime.Types.Result.GetResult<Prisma.$DiscountItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DiscountItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscountItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DiscountItems
   * const discountItems = await prisma.discountItem.findMany()
   * 
   * // Get first 10 DiscountItems
   * const discountItems = await prisma.discountItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const discountItemWithIdOnly = await prisma.discountItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DiscountItemFindManyArgs>(args?: Prisma.SelectSubset<T, DiscountItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DiscountItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DiscountItem.
   * @param {DiscountItemCreateArgs} args - Arguments to create a DiscountItem.
   * @example
   * // Create one DiscountItem
   * const DiscountItem = await prisma.discountItem.create({
   *   data: {
   *     // ... data to create a DiscountItem
   *   }
   * })
   * 
   */
  create<T extends DiscountItemCreateArgs>(args: Prisma.SelectSubset<T, DiscountItemCreateArgs<ExtArgs>>): Prisma.Prisma__DiscountItemClient<runtime.Types.Result.GetResult<Prisma.$DiscountItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DiscountItems.
   * @param {DiscountItemCreateManyArgs} args - Arguments to create many DiscountItems.
   * @example
   * // Create many DiscountItems
   * const discountItem = await prisma.discountItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DiscountItemCreateManyArgs>(args?: Prisma.SelectSubset<T, DiscountItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DiscountItems and returns the data saved in the database.
   * @param {DiscountItemCreateManyAndReturnArgs} args - Arguments to create many DiscountItems.
   * @example
   * // Create many DiscountItems
   * const discountItem = await prisma.discountItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DiscountItems and only return the `id`
   * const discountItemWithIdOnly = await prisma.discountItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DiscountItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DiscountItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DiscountItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DiscountItem.
   * @param {DiscountItemDeleteArgs} args - Arguments to delete one DiscountItem.
   * @example
   * // Delete one DiscountItem
   * const DiscountItem = await prisma.discountItem.delete({
   *   where: {
   *     // ... filter to delete one DiscountItem
   *   }
   * })
   * 
   */
  delete<T extends DiscountItemDeleteArgs>(args: Prisma.SelectSubset<T, DiscountItemDeleteArgs<ExtArgs>>): Prisma.Prisma__DiscountItemClient<runtime.Types.Result.GetResult<Prisma.$DiscountItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DiscountItem.
   * @param {DiscountItemUpdateArgs} args - Arguments to update one DiscountItem.
   * @example
   * // Update one DiscountItem
   * const discountItem = await prisma.discountItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DiscountItemUpdateArgs>(args: Prisma.SelectSubset<T, DiscountItemUpdateArgs<ExtArgs>>): Prisma.Prisma__DiscountItemClient<runtime.Types.Result.GetResult<Prisma.$DiscountItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DiscountItems.
   * @param {DiscountItemDeleteManyArgs} args - Arguments to filter DiscountItems to delete.
   * @example
   * // Delete a few DiscountItems
   * const { count } = await prisma.discountItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DiscountItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, DiscountItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DiscountItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscountItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DiscountItems
   * const discountItem = await prisma.discountItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DiscountItemUpdateManyArgs>(args: Prisma.SelectSubset<T, DiscountItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DiscountItems and returns the data updated in the database.
   * @param {DiscountItemUpdateManyAndReturnArgs} args - Arguments to update many DiscountItems.
   * @example
   * // Update many DiscountItems
   * const discountItem = await prisma.discountItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DiscountItems and only return the `id`
   * const discountItemWithIdOnly = await prisma.discountItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DiscountItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DiscountItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DiscountItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DiscountItem.
   * @param {DiscountItemUpsertArgs} args - Arguments to update or create a DiscountItem.
   * @example
   * // Update or create a DiscountItem
   * const discountItem = await prisma.discountItem.upsert({
   *   create: {
   *     // ... data to create a DiscountItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DiscountItem we want to update
   *   }
   * })
   */
  upsert<T extends DiscountItemUpsertArgs>(args: Prisma.SelectSubset<T, DiscountItemUpsertArgs<ExtArgs>>): Prisma.Prisma__DiscountItemClient<runtime.Types.Result.GetResult<Prisma.$DiscountItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DiscountItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscountItemCountArgs} args - Arguments to filter DiscountItems to count.
   * @example
   * // Count the number of DiscountItems
   * const count = await prisma.discountItem.count({
   *   where: {
   *     // ... the filter for the DiscountItems we want to count
   *   }
   * })
  **/
  count<T extends DiscountItemCountArgs>(
    args?: Prisma.Subset<T, DiscountItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DiscountItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DiscountItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscountItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DiscountItemAggregateArgs>(args: Prisma.Subset<T, DiscountItemAggregateArgs>): Prisma.PrismaPromise<GetDiscountItemAggregateType<T>>

  /**
   * Group by DiscountItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscountItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DiscountItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DiscountItemGroupByArgs['orderBy'] }
      : { orderBy?: DiscountItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DiscountItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDiscountItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DiscountItem model
 */
readonly fields: DiscountItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DiscountItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DiscountItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.CategoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CategoryDefaultArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DiscountItem model
 */
export interface DiscountItemFieldRefs {
  readonly id: Prisma.FieldRef<"DiscountItem", 'String'>
  readonly title: Prisma.FieldRef<"DiscountItem", 'String'>
  readonly subtitle: Prisma.FieldRef<"DiscountItem", 'String'>
  readonly description: Prisma.FieldRef<"DiscountItem", 'String'>
  readonly features: Prisma.FieldRef<"DiscountItem", 'String[]'>
  readonly buttonText: Prisma.FieldRef<"DiscountItem", 'String'>
  readonly categoryId: Prisma.FieldRef<"DiscountItem", 'String'>
  readonly productId: Prisma.FieldRef<"DiscountItem", 'String'>
  readonly createdAt: Prisma.FieldRef<"DiscountItem", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DiscountItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DiscountItem findUnique
 */
export type DiscountItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscountItem
   */
  select?: Prisma.DiscountItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscountItem
   */
  omit?: Prisma.DiscountItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscountItemInclude<ExtArgs> | null
  /**
   * Filter, which DiscountItem to fetch.
   */
  where: Prisma.DiscountItemWhereUniqueInput
}

/**
 * DiscountItem findUniqueOrThrow
 */
export type DiscountItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscountItem
   */
  select?: Prisma.DiscountItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscountItem
   */
  omit?: Prisma.DiscountItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscountItemInclude<ExtArgs> | null
  /**
   * Filter, which DiscountItem to fetch.
   */
  where: Prisma.DiscountItemWhereUniqueInput
}

/**
 * DiscountItem findFirst
 */
export type DiscountItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscountItem
   */
  select?: Prisma.DiscountItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscountItem
   */
  omit?: Prisma.DiscountItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscountItemInclude<ExtArgs> | null
  /**
   * Filter, which DiscountItem to fetch.
   */
  where?: Prisma.DiscountItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DiscountItems to fetch.
   */
  orderBy?: Prisma.DiscountItemOrderByWithRelationInput | Prisma.DiscountItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DiscountItems.
   */
  cursor?: Prisma.DiscountItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DiscountItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DiscountItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DiscountItems.
   */
  distinct?: Prisma.DiscountItemScalarFieldEnum | Prisma.DiscountItemScalarFieldEnum[]
}

/**
 * DiscountItem findFirstOrThrow
 */
export type DiscountItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscountItem
   */
  select?: Prisma.DiscountItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscountItem
   */
  omit?: Prisma.DiscountItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscountItemInclude<ExtArgs> | null
  /**
   * Filter, which DiscountItem to fetch.
   */
  where?: Prisma.DiscountItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DiscountItems to fetch.
   */
  orderBy?: Prisma.DiscountItemOrderByWithRelationInput | Prisma.DiscountItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DiscountItems.
   */
  cursor?: Prisma.DiscountItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DiscountItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DiscountItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DiscountItems.
   */
  distinct?: Prisma.DiscountItemScalarFieldEnum | Prisma.DiscountItemScalarFieldEnum[]
}

/**
 * DiscountItem findMany
 */
export type DiscountItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscountItem
   */
  select?: Prisma.DiscountItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscountItem
   */
  omit?: Prisma.DiscountItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscountItemInclude<ExtArgs> | null
  /**
   * Filter, which DiscountItems to fetch.
   */
  where?: Prisma.DiscountItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DiscountItems to fetch.
   */
  orderBy?: Prisma.DiscountItemOrderByWithRelationInput | Prisma.DiscountItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DiscountItems.
   */
  cursor?: Prisma.DiscountItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DiscountItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DiscountItems.
   */
  skip?: number
  distinct?: Prisma.DiscountItemScalarFieldEnum | Prisma.DiscountItemScalarFieldEnum[]
}

/**
 * DiscountItem create
 */
export type DiscountItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscountItem
   */
  select?: Prisma.DiscountItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscountItem
   */
  omit?: Prisma.DiscountItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscountItemInclude<ExtArgs> | null
  /**
   * The data needed to create a DiscountItem.
   */
  data: Prisma.XOR<Prisma.DiscountItemCreateInput, Prisma.DiscountItemUncheckedCreateInput>
}

/**
 * DiscountItem createMany
 */
export type DiscountItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DiscountItems.
   */
  data: Prisma.DiscountItemCreateManyInput | Prisma.DiscountItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DiscountItem createManyAndReturn
 */
export type DiscountItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscountItem
   */
  select?: Prisma.DiscountItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DiscountItem
   */
  omit?: Prisma.DiscountItemOmit<ExtArgs> | null
  /**
   * The data used to create many DiscountItems.
   */
  data: Prisma.DiscountItemCreateManyInput | Prisma.DiscountItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscountItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DiscountItem update
 */
export type DiscountItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscountItem
   */
  select?: Prisma.DiscountItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscountItem
   */
  omit?: Prisma.DiscountItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscountItemInclude<ExtArgs> | null
  /**
   * The data needed to update a DiscountItem.
   */
  data: Prisma.XOR<Prisma.DiscountItemUpdateInput, Prisma.DiscountItemUncheckedUpdateInput>
  /**
   * Choose, which DiscountItem to update.
   */
  where: Prisma.DiscountItemWhereUniqueInput
}

/**
 * DiscountItem updateMany
 */
export type DiscountItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DiscountItems.
   */
  data: Prisma.XOR<Prisma.DiscountItemUpdateManyMutationInput, Prisma.DiscountItemUncheckedUpdateManyInput>
  /**
   * Filter which DiscountItems to update
   */
  where?: Prisma.DiscountItemWhereInput
  /**
   * Limit how many DiscountItems to update.
   */
  limit?: number
}

/**
 * DiscountItem updateManyAndReturn
 */
export type DiscountItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscountItem
   */
  select?: Prisma.DiscountItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DiscountItem
   */
  omit?: Prisma.DiscountItemOmit<ExtArgs> | null
  /**
   * The data used to update DiscountItems.
   */
  data: Prisma.XOR<Prisma.DiscountItemUpdateManyMutationInput, Prisma.DiscountItemUncheckedUpdateManyInput>
  /**
   * Filter which DiscountItems to update
   */
  where?: Prisma.DiscountItemWhereInput
  /**
   * Limit how many DiscountItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscountItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DiscountItem upsert
 */
export type DiscountItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscountItem
   */
  select?: Prisma.DiscountItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscountItem
   */
  omit?: Prisma.DiscountItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscountItemInclude<ExtArgs> | null
  /**
   * The filter to search for the DiscountItem to update in case it exists.
   */
  where: Prisma.DiscountItemWhereUniqueInput
  /**
   * In case the DiscountItem found by the `where` argument doesn't exist, create a new DiscountItem with this data.
   */
  create: Prisma.XOR<Prisma.DiscountItemCreateInput, Prisma.DiscountItemUncheckedCreateInput>
  /**
   * In case the DiscountItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DiscountItemUpdateInput, Prisma.DiscountItemUncheckedUpdateInput>
}

/**
 * DiscountItem delete
 */
export type DiscountItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscountItem
   */
  select?: Prisma.DiscountItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscountItem
   */
  omit?: Prisma.DiscountItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscountItemInclude<ExtArgs> | null
  /**
   * Filter which DiscountItem to delete.
   */
  where: Prisma.DiscountItemWhereUniqueInput
}

/**
 * DiscountItem deleteMany
 */
export type DiscountItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DiscountItems to delete
   */
  where?: Prisma.DiscountItemWhereInput
  /**
   * Limit how many DiscountItems to delete.
   */
  limit?: number
}

/**
 * DiscountItem without action
 */
export type DiscountItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscountItem
   */
  select?: Prisma.DiscountItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscountItem
   */
  omit?: Prisma.DiscountItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscountItemInclude<ExtArgs> | null
}
