
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NavLink` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NavLink
 * 
 */
export type NavLinkModel = runtime.Types.Result.DefaultSelection<Prisma.$NavLinkPayload>

export type AggregateNavLink = {
  _count: NavLinkCountAggregateOutputType | null
  _avg: NavLinkAvgAggregateOutputType | null
  _sum: NavLinkSumAggregateOutputType | null
  _min: NavLinkMinAggregateOutputType | null
  _max: NavLinkMaxAggregateOutputType | null
}

export type NavLinkAvgAggregateOutputType = {
  order: number | null
}

export type NavLinkSumAggregateOutputType = {
  order: number | null
}

export type NavLinkMinAggregateOutputType = {
  id: string | null
  label: string | null
  url: string | null
  groupId: string | null
  order: number | null
}

export type NavLinkMaxAggregateOutputType = {
  id: string | null
  label: string | null
  url: string | null
  groupId: string | null
  order: number | null
}

export type NavLinkCountAggregateOutputType = {
  id: number
  label: number
  url: number
  groupId: number
  order: number
  _all: number
}


export type NavLinkAvgAggregateInputType = {
  order?: true
}

export type NavLinkSumAggregateInputType = {
  order?: true
}

export type NavLinkMinAggregateInputType = {
  id?: true
  label?: true
  url?: true
  groupId?: true
  order?: true
}

export type NavLinkMaxAggregateInputType = {
  id?: true
  label?: true
  url?: true
  groupId?: true
  order?: true
}

export type NavLinkCountAggregateInputType = {
  id?: true
  label?: true
  url?: true
  groupId?: true
  order?: true
  _all?: true
}

export type NavLinkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NavLink to aggregate.
   */
  where?: Prisma.NavLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NavLinks to fetch.
   */
  orderBy?: Prisma.NavLinkOrderByWithRelationInput | Prisma.NavLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NavLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NavLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NavLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NavLinks
  **/
  _count?: true | NavLinkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NavLinkAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NavLinkSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NavLinkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NavLinkMaxAggregateInputType
}

export type GetNavLinkAggregateType<T extends NavLinkAggregateArgs> = {
      [P in keyof T & keyof AggregateNavLink]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNavLink[P]>
    : Prisma.GetScalarType<T[P], AggregateNavLink[P]>
}




export type NavLinkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NavLinkWhereInput
  orderBy?: Prisma.NavLinkOrderByWithAggregationInput | Prisma.NavLinkOrderByWithAggregationInput[]
  by: Prisma.NavLinkScalarFieldEnum[] | Prisma.NavLinkScalarFieldEnum
  having?: Prisma.NavLinkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NavLinkCountAggregateInputType | true
  _avg?: NavLinkAvgAggregateInputType
  _sum?: NavLinkSumAggregateInputType
  _min?: NavLinkMinAggregateInputType
  _max?: NavLinkMaxAggregateInputType
}

export type NavLinkGroupByOutputType = {
  id: string
  label: string
  url: string
  groupId: string
  order: number
  _count: NavLinkCountAggregateOutputType | null
  _avg: NavLinkAvgAggregateOutputType | null
  _sum: NavLinkSumAggregateOutputType | null
  _min: NavLinkMinAggregateOutputType | null
  _max: NavLinkMaxAggregateOutputType | null
}

type GetNavLinkGroupByPayload<T extends NavLinkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NavLinkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NavLinkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NavLinkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NavLinkGroupByOutputType[P]>
      }
    >
  >



export type NavLinkWhereInput = {
  AND?: Prisma.NavLinkWhereInput | Prisma.NavLinkWhereInput[]
  OR?: Prisma.NavLinkWhereInput[]
  NOT?: Prisma.NavLinkWhereInput | Prisma.NavLinkWhereInput[]
  id?: Prisma.StringFilter<"NavLink"> | string
  label?: Prisma.StringFilter<"NavLink"> | string
  url?: Prisma.StringFilter<"NavLink"> | string
  groupId?: Prisma.StringFilter<"NavLink"> | string
  order?: Prisma.IntFilter<"NavLink"> | number
  group?: Prisma.XOR<Prisma.LinkGroupScalarRelationFilter, Prisma.LinkGroupWhereInput>
}

export type NavLinkOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  url?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  group?: Prisma.LinkGroupOrderByWithRelationInput
}

export type NavLinkWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.NavLinkWhereInput | Prisma.NavLinkWhereInput[]
  OR?: Prisma.NavLinkWhereInput[]
  NOT?: Prisma.NavLinkWhereInput | Prisma.NavLinkWhereInput[]
  label?: Prisma.StringFilter<"NavLink"> | string
  url?: Prisma.StringFilter<"NavLink"> | string
  groupId?: Prisma.StringFilter<"NavLink"> | string
  order?: Prisma.IntFilter<"NavLink"> | number
  group?: Prisma.XOR<Prisma.LinkGroupScalarRelationFilter, Prisma.LinkGroupWhereInput>
}, "id">

export type NavLinkOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  url?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  _count?: Prisma.NavLinkCountOrderByAggregateInput
  _avg?: Prisma.NavLinkAvgOrderByAggregateInput
  _max?: Prisma.NavLinkMaxOrderByAggregateInput
  _min?: Prisma.NavLinkMinOrderByAggregateInput
  _sum?: Prisma.NavLinkSumOrderByAggregateInput
}

export type NavLinkScalarWhereWithAggregatesInput = {
  AND?: Prisma.NavLinkScalarWhereWithAggregatesInput | Prisma.NavLinkScalarWhereWithAggregatesInput[]
  OR?: Prisma.NavLinkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NavLinkScalarWhereWithAggregatesInput | Prisma.NavLinkScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"NavLink"> | string
  label?: Prisma.StringWithAggregatesFilter<"NavLink"> | string
  url?: Prisma.StringWithAggregatesFilter<"NavLink"> | string
  groupId?: Prisma.StringWithAggregatesFilter<"NavLink"> | string
  order?: Prisma.IntWithAggregatesFilter<"NavLink"> | number
}

export type NavLinkCreateInput = {
  id?: string
  label: string
  url: string
  order?: number
  group: Prisma.LinkGroupCreateNestedOneWithoutLinksInput
}

export type NavLinkUncheckedCreateInput = {
  id?: string
  label: string
  url: string
  groupId: string
  order?: number
}

export type NavLinkUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  group?: Prisma.LinkGroupUpdateOneRequiredWithoutLinksNestedInput
}

export type NavLinkUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NavLinkCreateManyInput = {
  id?: string
  label: string
  url: string
  groupId: string
  order?: number
}

export type NavLinkUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NavLinkUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NavLinkListRelationFilter = {
  every?: Prisma.NavLinkWhereInput
  some?: Prisma.NavLinkWhereInput
  none?: Prisma.NavLinkWhereInput
}

export type NavLinkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NavLinkCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  url?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type NavLinkAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type NavLinkMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  url?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type NavLinkMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  url?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type NavLinkSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type NavLinkCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.NavLinkCreateWithoutGroupInput, Prisma.NavLinkUncheckedCreateWithoutGroupInput> | Prisma.NavLinkCreateWithoutGroupInput[] | Prisma.NavLinkUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.NavLinkCreateOrConnectWithoutGroupInput | Prisma.NavLinkCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.NavLinkCreateManyGroupInputEnvelope
  connect?: Prisma.NavLinkWhereUniqueInput | Prisma.NavLinkWhereUniqueInput[]
}

export type NavLinkUncheckedCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.NavLinkCreateWithoutGroupInput, Prisma.NavLinkUncheckedCreateWithoutGroupInput> | Prisma.NavLinkCreateWithoutGroupInput[] | Prisma.NavLinkUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.NavLinkCreateOrConnectWithoutGroupInput | Prisma.NavLinkCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.NavLinkCreateManyGroupInputEnvelope
  connect?: Prisma.NavLinkWhereUniqueInput | Prisma.NavLinkWhereUniqueInput[]
}

export type NavLinkUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.NavLinkCreateWithoutGroupInput, Prisma.NavLinkUncheckedCreateWithoutGroupInput> | Prisma.NavLinkCreateWithoutGroupInput[] | Prisma.NavLinkUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.NavLinkCreateOrConnectWithoutGroupInput | Prisma.NavLinkCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.NavLinkUpsertWithWhereUniqueWithoutGroupInput | Prisma.NavLinkUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.NavLinkCreateManyGroupInputEnvelope
  set?: Prisma.NavLinkWhereUniqueInput | Prisma.NavLinkWhereUniqueInput[]
  disconnect?: Prisma.NavLinkWhereUniqueInput | Prisma.NavLinkWhereUniqueInput[]
  delete?: Prisma.NavLinkWhereUniqueInput | Prisma.NavLinkWhereUniqueInput[]
  connect?: Prisma.NavLinkWhereUniqueInput | Prisma.NavLinkWhereUniqueInput[]
  update?: Prisma.NavLinkUpdateWithWhereUniqueWithoutGroupInput | Prisma.NavLinkUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.NavLinkUpdateManyWithWhereWithoutGroupInput | Prisma.NavLinkUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.NavLinkScalarWhereInput | Prisma.NavLinkScalarWhereInput[]
}

export type NavLinkUncheckedUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.NavLinkCreateWithoutGroupInput, Prisma.NavLinkUncheckedCreateWithoutGroupInput> | Prisma.NavLinkCreateWithoutGroupInput[] | Prisma.NavLinkUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.NavLinkCreateOrConnectWithoutGroupInput | Prisma.NavLinkCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.NavLinkUpsertWithWhereUniqueWithoutGroupInput | Prisma.NavLinkUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.NavLinkCreateManyGroupInputEnvelope
  set?: Prisma.NavLinkWhereUniqueInput | Prisma.NavLinkWhereUniqueInput[]
  disconnect?: Prisma.NavLinkWhereUniqueInput | Prisma.NavLinkWhereUniqueInput[]
  delete?: Prisma.NavLinkWhereUniqueInput | Prisma.NavLinkWhereUniqueInput[]
  connect?: Prisma.NavLinkWhereUniqueInput | Prisma.NavLinkWhereUniqueInput[]
  update?: Prisma.NavLinkUpdateWithWhereUniqueWithoutGroupInput | Prisma.NavLinkUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.NavLinkUpdateManyWithWhereWithoutGroupInput | Prisma.NavLinkUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.NavLinkScalarWhereInput | Prisma.NavLinkScalarWhereInput[]
}

export type NavLinkCreateWithoutGroupInput = {
  id?: string
  label: string
  url: string
  order?: number
}

export type NavLinkUncheckedCreateWithoutGroupInput = {
  id?: string
  label: string
  url: string
  order?: number
}

export type NavLinkCreateOrConnectWithoutGroupInput = {
  where: Prisma.NavLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.NavLinkCreateWithoutGroupInput, Prisma.NavLinkUncheckedCreateWithoutGroupInput>
}

export type NavLinkCreateManyGroupInputEnvelope = {
  data: Prisma.NavLinkCreateManyGroupInput | Prisma.NavLinkCreateManyGroupInput[]
  skipDuplicates?: boolean
}

export type NavLinkUpsertWithWhereUniqueWithoutGroupInput = {
  where: Prisma.NavLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.NavLinkUpdateWithoutGroupInput, Prisma.NavLinkUncheckedUpdateWithoutGroupInput>
  create: Prisma.XOR<Prisma.NavLinkCreateWithoutGroupInput, Prisma.NavLinkUncheckedCreateWithoutGroupInput>
}

export type NavLinkUpdateWithWhereUniqueWithoutGroupInput = {
  where: Prisma.NavLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.NavLinkUpdateWithoutGroupInput, Prisma.NavLinkUncheckedUpdateWithoutGroupInput>
}

export type NavLinkUpdateManyWithWhereWithoutGroupInput = {
  where: Prisma.NavLinkScalarWhereInput
  data: Prisma.XOR<Prisma.NavLinkUpdateManyMutationInput, Prisma.NavLinkUncheckedUpdateManyWithoutGroupInput>
}

export type NavLinkScalarWhereInput = {
  AND?: Prisma.NavLinkScalarWhereInput | Prisma.NavLinkScalarWhereInput[]
  OR?: Prisma.NavLinkScalarWhereInput[]
  NOT?: Prisma.NavLinkScalarWhereInput | Prisma.NavLinkScalarWhereInput[]
  id?: Prisma.StringFilter<"NavLink"> | string
  label?: Prisma.StringFilter<"NavLink"> | string
  url?: Prisma.StringFilter<"NavLink"> | string
  groupId?: Prisma.StringFilter<"NavLink"> | string
  order?: Prisma.IntFilter<"NavLink"> | number
}

export type NavLinkCreateManyGroupInput = {
  id?: string
  label: string
  url: string
  order?: number
}

export type NavLinkUpdateWithoutGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NavLinkUncheckedUpdateWithoutGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NavLinkUncheckedUpdateManyWithoutGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
}



export type NavLinkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  label?: boolean
  url?: boolean
  groupId?: boolean
  order?: boolean
  group?: boolean | Prisma.LinkGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["navLink"]>

export type NavLinkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  label?: boolean
  url?: boolean
  groupId?: boolean
  order?: boolean
  group?: boolean | Prisma.LinkGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["navLink"]>

export type NavLinkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  label?: boolean
  url?: boolean
  groupId?: boolean
  order?: boolean
  group?: boolean | Prisma.LinkGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["navLink"]>

export type NavLinkSelectScalar = {
  id?: boolean
  label?: boolean
  url?: boolean
  groupId?: boolean
  order?: boolean
}

export type NavLinkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "label" | "url" | "groupId" | "order", ExtArgs["result"]["navLink"]>
export type NavLinkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  group?: boolean | Prisma.LinkGroupDefaultArgs<ExtArgs>
}
export type NavLinkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  group?: boolean | Prisma.LinkGroupDefaultArgs<ExtArgs>
}
export type NavLinkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  group?: boolean | Prisma.LinkGroupDefaultArgs<ExtArgs>
}

export type $NavLinkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NavLink"
  objects: {
    group: Prisma.$LinkGroupPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    label: string
    url: string
    groupId: string
    order: number
  }, ExtArgs["result"]["navLink"]>
  composites: {}
}

export type NavLinkGetPayload<S extends boolean | null | undefined | NavLinkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NavLinkPayload, S>

export type NavLinkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NavLinkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NavLinkCountAggregateInputType | true
  }

export interface NavLinkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NavLink'], meta: { name: 'NavLink' } }
  /**
   * Find zero or one NavLink that matches the filter.
   * @param {NavLinkFindUniqueArgs} args - Arguments to find a NavLink
   * @example
   * // Get one NavLink
   * const navLink = await prisma.navLink.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NavLinkFindUniqueArgs>(args: Prisma.SelectSubset<T, NavLinkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NavLinkClient<runtime.Types.Result.GetResult<Prisma.$NavLinkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NavLink that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NavLinkFindUniqueOrThrowArgs} args - Arguments to find a NavLink
   * @example
   * // Get one NavLink
   * const navLink = await prisma.navLink.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NavLinkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NavLinkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NavLinkClient<runtime.Types.Result.GetResult<Prisma.$NavLinkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NavLink that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NavLinkFindFirstArgs} args - Arguments to find a NavLink
   * @example
   * // Get one NavLink
   * const navLink = await prisma.navLink.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NavLinkFindFirstArgs>(args?: Prisma.SelectSubset<T, NavLinkFindFirstArgs<ExtArgs>>): Prisma.Prisma__NavLinkClient<runtime.Types.Result.GetResult<Prisma.$NavLinkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NavLink that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NavLinkFindFirstOrThrowArgs} args - Arguments to find a NavLink
   * @example
   * // Get one NavLink
   * const navLink = await prisma.navLink.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NavLinkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NavLinkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NavLinkClient<runtime.Types.Result.GetResult<Prisma.$NavLinkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NavLinks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NavLinkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NavLinks
   * const navLinks = await prisma.navLink.findMany()
   * 
   * // Get first 10 NavLinks
   * const navLinks = await prisma.navLink.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const navLinkWithIdOnly = await prisma.navLink.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NavLinkFindManyArgs>(args?: Prisma.SelectSubset<T, NavLinkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NavLinkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NavLink.
   * @param {NavLinkCreateArgs} args - Arguments to create a NavLink.
   * @example
   * // Create one NavLink
   * const NavLink = await prisma.navLink.create({
   *   data: {
   *     // ... data to create a NavLink
   *   }
   * })
   * 
   */
  create<T extends NavLinkCreateArgs>(args: Prisma.SelectSubset<T, NavLinkCreateArgs<ExtArgs>>): Prisma.Prisma__NavLinkClient<runtime.Types.Result.GetResult<Prisma.$NavLinkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NavLinks.
   * @param {NavLinkCreateManyArgs} args - Arguments to create many NavLinks.
   * @example
   * // Create many NavLinks
   * const navLink = await prisma.navLink.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NavLinkCreateManyArgs>(args?: Prisma.SelectSubset<T, NavLinkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NavLinks and returns the data saved in the database.
   * @param {NavLinkCreateManyAndReturnArgs} args - Arguments to create many NavLinks.
   * @example
   * // Create many NavLinks
   * const navLink = await prisma.navLink.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NavLinks and only return the `id`
   * const navLinkWithIdOnly = await prisma.navLink.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NavLinkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NavLinkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NavLinkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NavLink.
   * @param {NavLinkDeleteArgs} args - Arguments to delete one NavLink.
   * @example
   * // Delete one NavLink
   * const NavLink = await prisma.navLink.delete({
   *   where: {
   *     // ... filter to delete one NavLink
   *   }
   * })
   * 
   */
  delete<T extends NavLinkDeleteArgs>(args: Prisma.SelectSubset<T, NavLinkDeleteArgs<ExtArgs>>): Prisma.Prisma__NavLinkClient<runtime.Types.Result.GetResult<Prisma.$NavLinkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NavLink.
   * @param {NavLinkUpdateArgs} args - Arguments to update one NavLink.
   * @example
   * // Update one NavLink
   * const navLink = await prisma.navLink.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NavLinkUpdateArgs>(args: Prisma.SelectSubset<T, NavLinkUpdateArgs<ExtArgs>>): Prisma.Prisma__NavLinkClient<runtime.Types.Result.GetResult<Prisma.$NavLinkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NavLinks.
   * @param {NavLinkDeleteManyArgs} args - Arguments to filter NavLinks to delete.
   * @example
   * // Delete a few NavLinks
   * const { count } = await prisma.navLink.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NavLinkDeleteManyArgs>(args?: Prisma.SelectSubset<T, NavLinkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NavLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NavLinkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NavLinks
   * const navLink = await prisma.navLink.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NavLinkUpdateManyArgs>(args: Prisma.SelectSubset<T, NavLinkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NavLinks and returns the data updated in the database.
   * @param {NavLinkUpdateManyAndReturnArgs} args - Arguments to update many NavLinks.
   * @example
   * // Update many NavLinks
   * const navLink = await prisma.navLink.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NavLinks and only return the `id`
   * const navLinkWithIdOnly = await prisma.navLink.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NavLinkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NavLinkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NavLinkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NavLink.
   * @param {NavLinkUpsertArgs} args - Arguments to update or create a NavLink.
   * @example
   * // Update or create a NavLink
   * const navLink = await prisma.navLink.upsert({
   *   create: {
   *     // ... data to create a NavLink
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NavLink we want to update
   *   }
   * })
   */
  upsert<T extends NavLinkUpsertArgs>(args: Prisma.SelectSubset<T, NavLinkUpsertArgs<ExtArgs>>): Prisma.Prisma__NavLinkClient<runtime.Types.Result.GetResult<Prisma.$NavLinkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NavLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NavLinkCountArgs} args - Arguments to filter NavLinks to count.
   * @example
   * // Count the number of NavLinks
   * const count = await prisma.navLink.count({
   *   where: {
   *     // ... the filter for the NavLinks we want to count
   *   }
   * })
  **/
  count<T extends NavLinkCountArgs>(
    args?: Prisma.Subset<T, NavLinkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NavLinkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NavLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NavLinkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NavLinkAggregateArgs>(args: Prisma.Subset<T, NavLinkAggregateArgs>): Prisma.PrismaPromise<GetNavLinkAggregateType<T>>

  /**
   * Group by NavLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NavLinkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NavLinkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NavLinkGroupByArgs['orderBy'] }
      : { orderBy?: NavLinkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NavLinkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNavLinkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NavLink model
 */
readonly fields: NavLinkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NavLink.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NavLinkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  group<T extends Prisma.LinkGroupDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LinkGroupDefaultArgs<ExtArgs>>): Prisma.Prisma__LinkGroupClient<runtime.Types.Result.GetResult<Prisma.$LinkGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NavLink model
 */
export interface NavLinkFieldRefs {
  readonly id: Prisma.FieldRef<"NavLink", 'String'>
  readonly label: Prisma.FieldRef<"NavLink", 'String'>
  readonly url: Prisma.FieldRef<"NavLink", 'String'>
  readonly groupId: Prisma.FieldRef<"NavLink", 'String'>
  readonly order: Prisma.FieldRef<"NavLink", 'Int'>
}
    

// Custom InputTypes
/**
 * NavLink findUnique
 */
export type NavLinkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NavLink
   */
  select?: Prisma.NavLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NavLink
   */
  omit?: Prisma.NavLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NavLinkInclude<ExtArgs> | null
  /**
   * Filter, which NavLink to fetch.
   */
  where: Prisma.NavLinkWhereUniqueInput
}

/**
 * NavLink findUniqueOrThrow
 */
export type NavLinkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NavLink
   */
  select?: Prisma.NavLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NavLink
   */
  omit?: Prisma.NavLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NavLinkInclude<ExtArgs> | null
  /**
   * Filter, which NavLink to fetch.
   */
  where: Prisma.NavLinkWhereUniqueInput
}

/**
 * NavLink findFirst
 */
export type NavLinkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NavLink
   */
  select?: Prisma.NavLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NavLink
   */
  omit?: Prisma.NavLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NavLinkInclude<ExtArgs> | null
  /**
   * Filter, which NavLink to fetch.
   */
  where?: Prisma.NavLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NavLinks to fetch.
   */
  orderBy?: Prisma.NavLinkOrderByWithRelationInput | Prisma.NavLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NavLinks.
   */
  cursor?: Prisma.NavLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NavLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NavLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NavLinks.
   */
  distinct?: Prisma.NavLinkScalarFieldEnum | Prisma.NavLinkScalarFieldEnum[]
}

/**
 * NavLink findFirstOrThrow
 */
export type NavLinkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NavLink
   */
  select?: Prisma.NavLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NavLink
   */
  omit?: Prisma.NavLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NavLinkInclude<ExtArgs> | null
  /**
   * Filter, which NavLink to fetch.
   */
  where?: Prisma.NavLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NavLinks to fetch.
   */
  orderBy?: Prisma.NavLinkOrderByWithRelationInput | Prisma.NavLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NavLinks.
   */
  cursor?: Prisma.NavLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NavLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NavLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NavLinks.
   */
  distinct?: Prisma.NavLinkScalarFieldEnum | Prisma.NavLinkScalarFieldEnum[]
}

/**
 * NavLink findMany
 */
export type NavLinkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NavLink
   */
  select?: Prisma.NavLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NavLink
   */
  omit?: Prisma.NavLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NavLinkInclude<ExtArgs> | null
  /**
   * Filter, which NavLinks to fetch.
   */
  where?: Prisma.NavLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NavLinks to fetch.
   */
  orderBy?: Prisma.NavLinkOrderByWithRelationInput | Prisma.NavLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NavLinks.
   */
  cursor?: Prisma.NavLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NavLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NavLinks.
   */
  skip?: number
  distinct?: Prisma.NavLinkScalarFieldEnum | Prisma.NavLinkScalarFieldEnum[]
}

/**
 * NavLink create
 */
export type NavLinkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NavLink
   */
  select?: Prisma.NavLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NavLink
   */
  omit?: Prisma.NavLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NavLinkInclude<ExtArgs> | null
  /**
   * The data needed to create a NavLink.
   */
  data: Prisma.XOR<Prisma.NavLinkCreateInput, Prisma.NavLinkUncheckedCreateInput>
}

/**
 * NavLink createMany
 */
export type NavLinkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NavLinks.
   */
  data: Prisma.NavLinkCreateManyInput | Prisma.NavLinkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NavLink createManyAndReturn
 */
export type NavLinkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NavLink
   */
  select?: Prisma.NavLinkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NavLink
   */
  omit?: Prisma.NavLinkOmit<ExtArgs> | null
  /**
   * The data used to create many NavLinks.
   */
  data: Prisma.NavLinkCreateManyInput | Prisma.NavLinkCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NavLinkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * NavLink update
 */
export type NavLinkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NavLink
   */
  select?: Prisma.NavLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NavLink
   */
  omit?: Prisma.NavLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NavLinkInclude<ExtArgs> | null
  /**
   * The data needed to update a NavLink.
   */
  data: Prisma.XOR<Prisma.NavLinkUpdateInput, Prisma.NavLinkUncheckedUpdateInput>
  /**
   * Choose, which NavLink to update.
   */
  where: Prisma.NavLinkWhereUniqueInput
}

/**
 * NavLink updateMany
 */
export type NavLinkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NavLinks.
   */
  data: Prisma.XOR<Prisma.NavLinkUpdateManyMutationInput, Prisma.NavLinkUncheckedUpdateManyInput>
  /**
   * Filter which NavLinks to update
   */
  where?: Prisma.NavLinkWhereInput
  /**
   * Limit how many NavLinks to update.
   */
  limit?: number
}

/**
 * NavLink updateManyAndReturn
 */
export type NavLinkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NavLink
   */
  select?: Prisma.NavLinkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NavLink
   */
  omit?: Prisma.NavLinkOmit<ExtArgs> | null
  /**
   * The data used to update NavLinks.
   */
  data: Prisma.XOR<Prisma.NavLinkUpdateManyMutationInput, Prisma.NavLinkUncheckedUpdateManyInput>
  /**
   * Filter which NavLinks to update
   */
  where?: Prisma.NavLinkWhereInput
  /**
   * Limit how many NavLinks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NavLinkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * NavLink upsert
 */
export type NavLinkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NavLink
   */
  select?: Prisma.NavLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NavLink
   */
  omit?: Prisma.NavLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NavLinkInclude<ExtArgs> | null
  /**
   * The filter to search for the NavLink to update in case it exists.
   */
  where: Prisma.NavLinkWhereUniqueInput
  /**
   * In case the NavLink found by the `where` argument doesn't exist, create a new NavLink with this data.
   */
  create: Prisma.XOR<Prisma.NavLinkCreateInput, Prisma.NavLinkUncheckedCreateInput>
  /**
   * In case the NavLink was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NavLinkUpdateInput, Prisma.NavLinkUncheckedUpdateInput>
}

/**
 * NavLink delete
 */
export type NavLinkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NavLink
   */
  select?: Prisma.NavLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NavLink
   */
  omit?: Prisma.NavLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NavLinkInclude<ExtArgs> | null
  /**
   * Filter which NavLink to delete.
   */
  where: Prisma.NavLinkWhereUniqueInput
}

/**
 * NavLink deleteMany
 */
export type NavLinkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NavLinks to delete
   */
  where?: Prisma.NavLinkWhereInput
  /**
   * Limit how many NavLinks to delete.
   */
  limit?: number
}

/**
 * NavLink without action
 */
export type NavLinkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NavLink
   */
  select?: Prisma.NavLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NavLink
   */
  omit?: Prisma.NavLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NavLinkInclude<ExtArgs> | null
}
