
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PromoBanner` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PromoBanner
 * 
 */
export type PromoBannerModel = runtime.Types.Result.DefaultSelection<Prisma.$PromoBannerPayload>

export type AggregatePromoBanner = {
  _count: PromoBannerCountAggregateOutputType | null
  _min: PromoBannerMinAggregateOutputType | null
  _max: PromoBannerMaxAggregateOutputType | null
}

export type PromoBannerMinAggregateOutputType = {
  id: string | null
  title: string | null
  productId: string | null
  customImage: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PromoBannerMaxAggregateOutputType = {
  id: string | null
  title: string | null
  productId: string | null
  customImage: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PromoBannerCountAggregateOutputType = {
  id: number
  title: number
  features: number
  productId: number
  customImage: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PromoBannerMinAggregateInputType = {
  id?: true
  title?: true
  productId?: true
  customImage?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type PromoBannerMaxAggregateInputType = {
  id?: true
  title?: true
  productId?: true
  customImage?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type PromoBannerCountAggregateInputType = {
  id?: true
  title?: true
  features?: true
  productId?: true
  customImage?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PromoBannerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PromoBanner to aggregate.
   */
  where?: Prisma.PromoBannerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PromoBanners to fetch.
   */
  orderBy?: Prisma.PromoBannerOrderByWithRelationInput | Prisma.PromoBannerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PromoBannerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PromoBanners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PromoBanners.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PromoBanners
  **/
  _count?: true | PromoBannerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PromoBannerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PromoBannerMaxAggregateInputType
}

export type GetPromoBannerAggregateType<T extends PromoBannerAggregateArgs> = {
      [P in keyof T & keyof AggregatePromoBanner]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePromoBanner[P]>
    : Prisma.GetScalarType<T[P], AggregatePromoBanner[P]>
}




export type PromoBannerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PromoBannerWhereInput
  orderBy?: Prisma.PromoBannerOrderByWithAggregationInput | Prisma.PromoBannerOrderByWithAggregationInput[]
  by: Prisma.PromoBannerScalarFieldEnum[] | Prisma.PromoBannerScalarFieldEnum
  having?: Prisma.PromoBannerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PromoBannerCountAggregateInputType | true
  _min?: PromoBannerMinAggregateInputType
  _max?: PromoBannerMaxAggregateInputType
}

export type PromoBannerGroupByOutputType = {
  id: string
  title: string
  features: string[]
  productId: string
  customImage: string | null
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: PromoBannerCountAggregateOutputType | null
  _min: PromoBannerMinAggregateOutputType | null
  _max: PromoBannerMaxAggregateOutputType | null
}

type GetPromoBannerGroupByPayload<T extends PromoBannerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PromoBannerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PromoBannerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PromoBannerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PromoBannerGroupByOutputType[P]>
      }
    >
  >



export type PromoBannerWhereInput = {
  AND?: Prisma.PromoBannerWhereInput | Prisma.PromoBannerWhereInput[]
  OR?: Prisma.PromoBannerWhereInput[]
  NOT?: Prisma.PromoBannerWhereInput | Prisma.PromoBannerWhereInput[]
  id?: Prisma.StringFilter<"PromoBanner"> | string
  title?: Prisma.StringFilter<"PromoBanner"> | string
  features?: Prisma.StringNullableListFilter<"PromoBanner">
  productId?: Prisma.StringFilter<"PromoBanner"> | string
  customImage?: Prisma.StringNullableFilter<"PromoBanner"> | string | null
  isActive?: Prisma.BoolFilter<"PromoBanner"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PromoBanner"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PromoBanner"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type PromoBannerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  features?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  customImage?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
}

export type PromoBannerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PromoBannerWhereInput | Prisma.PromoBannerWhereInput[]
  OR?: Prisma.PromoBannerWhereInput[]
  NOT?: Prisma.PromoBannerWhereInput | Prisma.PromoBannerWhereInput[]
  title?: Prisma.StringFilter<"PromoBanner"> | string
  features?: Prisma.StringNullableListFilter<"PromoBanner">
  productId?: Prisma.StringFilter<"PromoBanner"> | string
  customImage?: Prisma.StringNullableFilter<"PromoBanner"> | string | null
  isActive?: Prisma.BoolFilter<"PromoBanner"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PromoBanner"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PromoBanner"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id">

export type PromoBannerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  features?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  customImage?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PromoBannerCountOrderByAggregateInput
  _max?: Prisma.PromoBannerMaxOrderByAggregateInput
  _min?: Prisma.PromoBannerMinOrderByAggregateInput
}

export type PromoBannerScalarWhereWithAggregatesInput = {
  AND?: Prisma.PromoBannerScalarWhereWithAggregatesInput | Prisma.PromoBannerScalarWhereWithAggregatesInput[]
  OR?: Prisma.PromoBannerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PromoBannerScalarWhereWithAggregatesInput | Prisma.PromoBannerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PromoBanner"> | string
  title?: Prisma.StringWithAggregatesFilter<"PromoBanner"> | string
  features?: Prisma.StringNullableListFilter<"PromoBanner">
  productId?: Prisma.StringWithAggregatesFilter<"PromoBanner"> | string
  customImage?: Prisma.StringNullableWithAggregatesFilter<"PromoBanner"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"PromoBanner"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PromoBanner"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PromoBanner"> | Date | string
}

export type PromoBannerCreateInput = {
  id?: string
  title: string
  features?: Prisma.PromoBannerCreatefeaturesInput | string[]
  customImage?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutPromoBannersInput
}

export type PromoBannerUncheckedCreateInput = {
  id?: string
  title: string
  features?: Prisma.PromoBannerCreatefeaturesInput | string[]
  productId: string
  customImage?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PromoBannerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.PromoBannerUpdatefeaturesInput | string[]
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutPromoBannersNestedInput
}

export type PromoBannerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.PromoBannerUpdatefeaturesInput | string[]
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PromoBannerCreateManyInput = {
  id?: string
  title: string
  features?: Prisma.PromoBannerCreatefeaturesInput | string[]
  productId: string
  customImage?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PromoBannerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.PromoBannerUpdatefeaturesInput | string[]
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PromoBannerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.PromoBannerUpdatefeaturesInput | string[]
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PromoBannerListRelationFilter = {
  every?: Prisma.PromoBannerWhereInput
  some?: Prisma.PromoBannerWhereInput
  none?: Prisma.PromoBannerWhereInput
}

export type PromoBannerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PromoBannerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  features?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  customImage?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PromoBannerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  customImage?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PromoBannerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  customImage?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PromoBannerCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.PromoBannerCreateWithoutProductInput, Prisma.PromoBannerUncheckedCreateWithoutProductInput> | Prisma.PromoBannerCreateWithoutProductInput[] | Prisma.PromoBannerUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.PromoBannerCreateOrConnectWithoutProductInput | Prisma.PromoBannerCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.PromoBannerCreateManyProductInputEnvelope
  connect?: Prisma.PromoBannerWhereUniqueInput | Prisma.PromoBannerWhereUniqueInput[]
}

export type PromoBannerUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.PromoBannerCreateWithoutProductInput, Prisma.PromoBannerUncheckedCreateWithoutProductInput> | Prisma.PromoBannerCreateWithoutProductInput[] | Prisma.PromoBannerUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.PromoBannerCreateOrConnectWithoutProductInput | Prisma.PromoBannerCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.PromoBannerCreateManyProductInputEnvelope
  connect?: Prisma.PromoBannerWhereUniqueInput | Prisma.PromoBannerWhereUniqueInput[]
}

export type PromoBannerUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.PromoBannerCreateWithoutProductInput, Prisma.PromoBannerUncheckedCreateWithoutProductInput> | Prisma.PromoBannerCreateWithoutProductInput[] | Prisma.PromoBannerUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.PromoBannerCreateOrConnectWithoutProductInput | Prisma.PromoBannerCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.PromoBannerUpsertWithWhereUniqueWithoutProductInput | Prisma.PromoBannerUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.PromoBannerCreateManyProductInputEnvelope
  set?: Prisma.PromoBannerWhereUniqueInput | Prisma.PromoBannerWhereUniqueInput[]
  disconnect?: Prisma.PromoBannerWhereUniqueInput | Prisma.PromoBannerWhereUniqueInput[]
  delete?: Prisma.PromoBannerWhereUniqueInput | Prisma.PromoBannerWhereUniqueInput[]
  connect?: Prisma.PromoBannerWhereUniqueInput | Prisma.PromoBannerWhereUniqueInput[]
  update?: Prisma.PromoBannerUpdateWithWhereUniqueWithoutProductInput | Prisma.PromoBannerUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.PromoBannerUpdateManyWithWhereWithoutProductInput | Prisma.PromoBannerUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.PromoBannerScalarWhereInput | Prisma.PromoBannerScalarWhereInput[]
}

export type PromoBannerUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.PromoBannerCreateWithoutProductInput, Prisma.PromoBannerUncheckedCreateWithoutProductInput> | Prisma.PromoBannerCreateWithoutProductInput[] | Prisma.PromoBannerUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.PromoBannerCreateOrConnectWithoutProductInput | Prisma.PromoBannerCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.PromoBannerUpsertWithWhereUniqueWithoutProductInput | Prisma.PromoBannerUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.PromoBannerCreateManyProductInputEnvelope
  set?: Prisma.PromoBannerWhereUniqueInput | Prisma.PromoBannerWhereUniqueInput[]
  disconnect?: Prisma.PromoBannerWhereUniqueInput | Prisma.PromoBannerWhereUniqueInput[]
  delete?: Prisma.PromoBannerWhereUniqueInput | Prisma.PromoBannerWhereUniqueInput[]
  connect?: Prisma.PromoBannerWhereUniqueInput | Prisma.PromoBannerWhereUniqueInput[]
  update?: Prisma.PromoBannerUpdateWithWhereUniqueWithoutProductInput | Prisma.PromoBannerUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.PromoBannerUpdateManyWithWhereWithoutProductInput | Prisma.PromoBannerUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.PromoBannerScalarWhereInput | Prisma.PromoBannerScalarWhereInput[]
}

export type PromoBannerCreatefeaturesInput = {
  set: string[]
}

export type PromoBannerUpdatefeaturesInput = {
  set?: string[]
  push?: string | string[]
}

export type PromoBannerCreateWithoutProductInput = {
  id?: string
  title: string
  features?: Prisma.PromoBannerCreatefeaturesInput | string[]
  customImage?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PromoBannerUncheckedCreateWithoutProductInput = {
  id?: string
  title: string
  features?: Prisma.PromoBannerCreatefeaturesInput | string[]
  customImage?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PromoBannerCreateOrConnectWithoutProductInput = {
  where: Prisma.PromoBannerWhereUniqueInput
  create: Prisma.XOR<Prisma.PromoBannerCreateWithoutProductInput, Prisma.PromoBannerUncheckedCreateWithoutProductInput>
}

export type PromoBannerCreateManyProductInputEnvelope = {
  data: Prisma.PromoBannerCreateManyProductInput | Prisma.PromoBannerCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type PromoBannerUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.PromoBannerWhereUniqueInput
  update: Prisma.XOR<Prisma.PromoBannerUpdateWithoutProductInput, Prisma.PromoBannerUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.PromoBannerCreateWithoutProductInput, Prisma.PromoBannerUncheckedCreateWithoutProductInput>
}

export type PromoBannerUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.PromoBannerWhereUniqueInput
  data: Prisma.XOR<Prisma.PromoBannerUpdateWithoutProductInput, Prisma.PromoBannerUncheckedUpdateWithoutProductInput>
}

export type PromoBannerUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.PromoBannerScalarWhereInput
  data: Prisma.XOR<Prisma.PromoBannerUpdateManyMutationInput, Prisma.PromoBannerUncheckedUpdateManyWithoutProductInput>
}

export type PromoBannerScalarWhereInput = {
  AND?: Prisma.PromoBannerScalarWhereInput | Prisma.PromoBannerScalarWhereInput[]
  OR?: Prisma.PromoBannerScalarWhereInput[]
  NOT?: Prisma.PromoBannerScalarWhereInput | Prisma.PromoBannerScalarWhereInput[]
  id?: Prisma.StringFilter<"PromoBanner"> | string
  title?: Prisma.StringFilter<"PromoBanner"> | string
  features?: Prisma.StringNullableListFilter<"PromoBanner">
  productId?: Prisma.StringFilter<"PromoBanner"> | string
  customImage?: Prisma.StringNullableFilter<"PromoBanner"> | string | null
  isActive?: Prisma.BoolFilter<"PromoBanner"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PromoBanner"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PromoBanner"> | Date | string
}

export type PromoBannerCreateManyProductInput = {
  id?: string
  title: string
  features?: Prisma.PromoBannerCreatefeaturesInput | string[]
  customImage?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PromoBannerUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.PromoBannerUpdatefeaturesInput | string[]
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PromoBannerUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.PromoBannerUpdatefeaturesInput | string[]
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PromoBannerUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  features?: Prisma.PromoBannerUpdatefeaturesInput | string[]
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PromoBannerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  features?: boolean
  productId?: boolean
  customImage?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["promoBanner"]>

export type PromoBannerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  features?: boolean
  productId?: boolean
  customImage?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["promoBanner"]>

export type PromoBannerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  features?: boolean
  productId?: boolean
  customImage?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["promoBanner"]>

export type PromoBannerSelectScalar = {
  id?: boolean
  title?: boolean
  features?: boolean
  productId?: boolean
  customImage?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PromoBannerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "features" | "productId" | "customImage" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["promoBanner"]>
export type PromoBannerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type PromoBannerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type PromoBannerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $PromoBannerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PromoBanner"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    features: string[]
    productId: string
    customImage: string | null
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["promoBanner"]>
  composites: {}
}

export type PromoBannerGetPayload<S extends boolean | null | undefined | PromoBannerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PromoBannerPayload, S>

export type PromoBannerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PromoBannerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PromoBannerCountAggregateInputType | true
  }

export interface PromoBannerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PromoBanner'], meta: { name: 'PromoBanner' } }
  /**
   * Find zero or one PromoBanner that matches the filter.
   * @param {PromoBannerFindUniqueArgs} args - Arguments to find a PromoBanner
   * @example
   * // Get one PromoBanner
   * const promoBanner = await prisma.promoBanner.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PromoBannerFindUniqueArgs>(args: Prisma.SelectSubset<T, PromoBannerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PromoBannerClient<runtime.Types.Result.GetResult<Prisma.$PromoBannerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PromoBanner that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PromoBannerFindUniqueOrThrowArgs} args - Arguments to find a PromoBanner
   * @example
   * // Get one PromoBanner
   * const promoBanner = await prisma.promoBanner.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PromoBannerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PromoBannerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PromoBannerClient<runtime.Types.Result.GetResult<Prisma.$PromoBannerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PromoBanner that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoBannerFindFirstArgs} args - Arguments to find a PromoBanner
   * @example
   * // Get one PromoBanner
   * const promoBanner = await prisma.promoBanner.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PromoBannerFindFirstArgs>(args?: Prisma.SelectSubset<T, PromoBannerFindFirstArgs<ExtArgs>>): Prisma.Prisma__PromoBannerClient<runtime.Types.Result.GetResult<Prisma.$PromoBannerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PromoBanner that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoBannerFindFirstOrThrowArgs} args - Arguments to find a PromoBanner
   * @example
   * // Get one PromoBanner
   * const promoBanner = await prisma.promoBanner.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PromoBannerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PromoBannerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PromoBannerClient<runtime.Types.Result.GetResult<Prisma.$PromoBannerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PromoBanners that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoBannerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PromoBanners
   * const promoBanners = await prisma.promoBanner.findMany()
   * 
   * // Get first 10 PromoBanners
   * const promoBanners = await prisma.promoBanner.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const promoBannerWithIdOnly = await prisma.promoBanner.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PromoBannerFindManyArgs>(args?: Prisma.SelectSubset<T, PromoBannerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PromoBannerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PromoBanner.
   * @param {PromoBannerCreateArgs} args - Arguments to create a PromoBanner.
   * @example
   * // Create one PromoBanner
   * const PromoBanner = await prisma.promoBanner.create({
   *   data: {
   *     // ... data to create a PromoBanner
   *   }
   * })
   * 
   */
  create<T extends PromoBannerCreateArgs>(args: Prisma.SelectSubset<T, PromoBannerCreateArgs<ExtArgs>>): Prisma.Prisma__PromoBannerClient<runtime.Types.Result.GetResult<Prisma.$PromoBannerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PromoBanners.
   * @param {PromoBannerCreateManyArgs} args - Arguments to create many PromoBanners.
   * @example
   * // Create many PromoBanners
   * const promoBanner = await prisma.promoBanner.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PromoBannerCreateManyArgs>(args?: Prisma.SelectSubset<T, PromoBannerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PromoBanners and returns the data saved in the database.
   * @param {PromoBannerCreateManyAndReturnArgs} args - Arguments to create many PromoBanners.
   * @example
   * // Create many PromoBanners
   * const promoBanner = await prisma.promoBanner.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PromoBanners and only return the `id`
   * const promoBannerWithIdOnly = await prisma.promoBanner.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PromoBannerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PromoBannerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PromoBannerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PromoBanner.
   * @param {PromoBannerDeleteArgs} args - Arguments to delete one PromoBanner.
   * @example
   * // Delete one PromoBanner
   * const PromoBanner = await prisma.promoBanner.delete({
   *   where: {
   *     // ... filter to delete one PromoBanner
   *   }
   * })
   * 
   */
  delete<T extends PromoBannerDeleteArgs>(args: Prisma.SelectSubset<T, PromoBannerDeleteArgs<ExtArgs>>): Prisma.Prisma__PromoBannerClient<runtime.Types.Result.GetResult<Prisma.$PromoBannerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PromoBanner.
   * @param {PromoBannerUpdateArgs} args - Arguments to update one PromoBanner.
   * @example
   * // Update one PromoBanner
   * const promoBanner = await prisma.promoBanner.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PromoBannerUpdateArgs>(args: Prisma.SelectSubset<T, PromoBannerUpdateArgs<ExtArgs>>): Prisma.Prisma__PromoBannerClient<runtime.Types.Result.GetResult<Prisma.$PromoBannerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PromoBanners.
   * @param {PromoBannerDeleteManyArgs} args - Arguments to filter PromoBanners to delete.
   * @example
   * // Delete a few PromoBanners
   * const { count } = await prisma.promoBanner.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PromoBannerDeleteManyArgs>(args?: Prisma.SelectSubset<T, PromoBannerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PromoBanners.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoBannerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PromoBanners
   * const promoBanner = await prisma.promoBanner.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PromoBannerUpdateManyArgs>(args: Prisma.SelectSubset<T, PromoBannerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PromoBanners and returns the data updated in the database.
   * @param {PromoBannerUpdateManyAndReturnArgs} args - Arguments to update many PromoBanners.
   * @example
   * // Update many PromoBanners
   * const promoBanner = await prisma.promoBanner.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PromoBanners and only return the `id`
   * const promoBannerWithIdOnly = await prisma.promoBanner.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PromoBannerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PromoBannerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PromoBannerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PromoBanner.
   * @param {PromoBannerUpsertArgs} args - Arguments to update or create a PromoBanner.
   * @example
   * // Update or create a PromoBanner
   * const promoBanner = await prisma.promoBanner.upsert({
   *   create: {
   *     // ... data to create a PromoBanner
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PromoBanner we want to update
   *   }
   * })
   */
  upsert<T extends PromoBannerUpsertArgs>(args: Prisma.SelectSubset<T, PromoBannerUpsertArgs<ExtArgs>>): Prisma.Prisma__PromoBannerClient<runtime.Types.Result.GetResult<Prisma.$PromoBannerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PromoBanners.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoBannerCountArgs} args - Arguments to filter PromoBanners to count.
   * @example
   * // Count the number of PromoBanners
   * const count = await prisma.promoBanner.count({
   *   where: {
   *     // ... the filter for the PromoBanners we want to count
   *   }
   * })
  **/
  count<T extends PromoBannerCountArgs>(
    args?: Prisma.Subset<T, PromoBannerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PromoBannerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PromoBanner.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoBannerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PromoBannerAggregateArgs>(args: Prisma.Subset<T, PromoBannerAggregateArgs>): Prisma.PrismaPromise<GetPromoBannerAggregateType<T>>

  /**
   * Group by PromoBanner.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromoBannerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PromoBannerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PromoBannerGroupByArgs['orderBy'] }
      : { orderBy?: PromoBannerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PromoBannerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPromoBannerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PromoBanner model
 */
readonly fields: PromoBannerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PromoBanner.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PromoBannerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PromoBanner model
 */
export interface PromoBannerFieldRefs {
  readonly id: Prisma.FieldRef<"PromoBanner", 'String'>
  readonly title: Prisma.FieldRef<"PromoBanner", 'String'>
  readonly features: Prisma.FieldRef<"PromoBanner", 'String[]'>
  readonly productId: Prisma.FieldRef<"PromoBanner", 'String'>
  readonly customImage: Prisma.FieldRef<"PromoBanner", 'String'>
  readonly isActive: Prisma.FieldRef<"PromoBanner", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"PromoBanner", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PromoBanner", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PromoBanner findUnique
 */
export type PromoBannerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoBanner
   */
  select?: Prisma.PromoBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoBanner
   */
  omit?: Prisma.PromoBannerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoBannerInclude<ExtArgs> | null
  /**
   * Filter, which PromoBanner to fetch.
   */
  where: Prisma.PromoBannerWhereUniqueInput
}

/**
 * PromoBanner findUniqueOrThrow
 */
export type PromoBannerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoBanner
   */
  select?: Prisma.PromoBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoBanner
   */
  omit?: Prisma.PromoBannerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoBannerInclude<ExtArgs> | null
  /**
   * Filter, which PromoBanner to fetch.
   */
  where: Prisma.PromoBannerWhereUniqueInput
}

/**
 * PromoBanner findFirst
 */
export type PromoBannerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoBanner
   */
  select?: Prisma.PromoBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoBanner
   */
  omit?: Prisma.PromoBannerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoBannerInclude<ExtArgs> | null
  /**
   * Filter, which PromoBanner to fetch.
   */
  where?: Prisma.PromoBannerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PromoBanners to fetch.
   */
  orderBy?: Prisma.PromoBannerOrderByWithRelationInput | Prisma.PromoBannerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PromoBanners.
   */
  cursor?: Prisma.PromoBannerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PromoBanners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PromoBanners.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PromoBanners.
   */
  distinct?: Prisma.PromoBannerScalarFieldEnum | Prisma.PromoBannerScalarFieldEnum[]
}

/**
 * PromoBanner findFirstOrThrow
 */
export type PromoBannerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoBanner
   */
  select?: Prisma.PromoBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoBanner
   */
  omit?: Prisma.PromoBannerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoBannerInclude<ExtArgs> | null
  /**
   * Filter, which PromoBanner to fetch.
   */
  where?: Prisma.PromoBannerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PromoBanners to fetch.
   */
  orderBy?: Prisma.PromoBannerOrderByWithRelationInput | Prisma.PromoBannerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PromoBanners.
   */
  cursor?: Prisma.PromoBannerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PromoBanners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PromoBanners.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PromoBanners.
   */
  distinct?: Prisma.PromoBannerScalarFieldEnum | Prisma.PromoBannerScalarFieldEnum[]
}

/**
 * PromoBanner findMany
 */
export type PromoBannerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoBanner
   */
  select?: Prisma.PromoBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoBanner
   */
  omit?: Prisma.PromoBannerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoBannerInclude<ExtArgs> | null
  /**
   * Filter, which PromoBanners to fetch.
   */
  where?: Prisma.PromoBannerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PromoBanners to fetch.
   */
  orderBy?: Prisma.PromoBannerOrderByWithRelationInput | Prisma.PromoBannerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PromoBanners.
   */
  cursor?: Prisma.PromoBannerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PromoBanners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PromoBanners.
   */
  skip?: number
  distinct?: Prisma.PromoBannerScalarFieldEnum | Prisma.PromoBannerScalarFieldEnum[]
}

/**
 * PromoBanner create
 */
export type PromoBannerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoBanner
   */
  select?: Prisma.PromoBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoBanner
   */
  omit?: Prisma.PromoBannerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoBannerInclude<ExtArgs> | null
  /**
   * The data needed to create a PromoBanner.
   */
  data: Prisma.XOR<Prisma.PromoBannerCreateInput, Prisma.PromoBannerUncheckedCreateInput>
}

/**
 * PromoBanner createMany
 */
export type PromoBannerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PromoBanners.
   */
  data: Prisma.PromoBannerCreateManyInput | Prisma.PromoBannerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PromoBanner createManyAndReturn
 */
export type PromoBannerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoBanner
   */
  select?: Prisma.PromoBannerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PromoBanner
   */
  omit?: Prisma.PromoBannerOmit<ExtArgs> | null
  /**
   * The data used to create many PromoBanners.
   */
  data: Prisma.PromoBannerCreateManyInput | Prisma.PromoBannerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoBannerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PromoBanner update
 */
export type PromoBannerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoBanner
   */
  select?: Prisma.PromoBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoBanner
   */
  omit?: Prisma.PromoBannerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoBannerInclude<ExtArgs> | null
  /**
   * The data needed to update a PromoBanner.
   */
  data: Prisma.XOR<Prisma.PromoBannerUpdateInput, Prisma.PromoBannerUncheckedUpdateInput>
  /**
   * Choose, which PromoBanner to update.
   */
  where: Prisma.PromoBannerWhereUniqueInput
}

/**
 * PromoBanner updateMany
 */
export type PromoBannerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PromoBanners.
   */
  data: Prisma.XOR<Prisma.PromoBannerUpdateManyMutationInput, Prisma.PromoBannerUncheckedUpdateManyInput>
  /**
   * Filter which PromoBanners to update
   */
  where?: Prisma.PromoBannerWhereInput
  /**
   * Limit how many PromoBanners to update.
   */
  limit?: number
}

/**
 * PromoBanner updateManyAndReturn
 */
export type PromoBannerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoBanner
   */
  select?: Prisma.PromoBannerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PromoBanner
   */
  omit?: Prisma.PromoBannerOmit<ExtArgs> | null
  /**
   * The data used to update PromoBanners.
   */
  data: Prisma.XOR<Prisma.PromoBannerUpdateManyMutationInput, Prisma.PromoBannerUncheckedUpdateManyInput>
  /**
   * Filter which PromoBanners to update
   */
  where?: Prisma.PromoBannerWhereInput
  /**
   * Limit how many PromoBanners to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoBannerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PromoBanner upsert
 */
export type PromoBannerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoBanner
   */
  select?: Prisma.PromoBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoBanner
   */
  omit?: Prisma.PromoBannerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoBannerInclude<ExtArgs> | null
  /**
   * The filter to search for the PromoBanner to update in case it exists.
   */
  where: Prisma.PromoBannerWhereUniqueInput
  /**
   * In case the PromoBanner found by the `where` argument doesn't exist, create a new PromoBanner with this data.
   */
  create: Prisma.XOR<Prisma.PromoBannerCreateInput, Prisma.PromoBannerUncheckedCreateInput>
  /**
   * In case the PromoBanner was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PromoBannerUpdateInput, Prisma.PromoBannerUncheckedUpdateInput>
}

/**
 * PromoBanner delete
 */
export type PromoBannerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoBanner
   */
  select?: Prisma.PromoBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoBanner
   */
  omit?: Prisma.PromoBannerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoBannerInclude<ExtArgs> | null
  /**
   * Filter which PromoBanner to delete.
   */
  where: Prisma.PromoBannerWhereUniqueInput
}

/**
 * PromoBanner deleteMany
 */
export type PromoBannerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PromoBanners to delete
   */
  where?: Prisma.PromoBannerWhereInput
  /**
   * Limit how many PromoBanners to delete.
   */
  limit?: number
}

/**
 * PromoBanner without action
 */
export type PromoBannerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromoBanner
   */
  select?: Prisma.PromoBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromoBanner
   */
  omit?: Prisma.PromoBannerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromoBannerInclude<ExtArgs> | null
}
