
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TrendingPromo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TrendingPromo
 * 
 */
export type TrendingPromoModel = runtime.Types.Result.DefaultSelection<Prisma.$TrendingPromoPayload>

export type AggregateTrendingPromo = {
  _count: TrendingPromoCountAggregateOutputType | null
  _min: TrendingPromoMinAggregateOutputType | null
  _max: TrendingPromoMaxAggregateOutputType | null
}

export type TrendingPromoMinAggregateOutputType = {
  id: string | null
  title: string | null
  linkText: string | null
  linkUrl: string | null
  imageUrl: string | null
  bgColor: string | null
  isActive: boolean | null
}

export type TrendingPromoMaxAggregateOutputType = {
  id: string | null
  title: string | null
  linkText: string | null
  linkUrl: string | null
  imageUrl: string | null
  bgColor: string | null
  isActive: boolean | null
}

export type TrendingPromoCountAggregateOutputType = {
  id: number
  title: number
  linkText: number
  linkUrl: number
  imageUrl: number
  bgColor: number
  isActive: number
  _all: number
}


export type TrendingPromoMinAggregateInputType = {
  id?: true
  title?: true
  linkText?: true
  linkUrl?: true
  imageUrl?: true
  bgColor?: true
  isActive?: true
}

export type TrendingPromoMaxAggregateInputType = {
  id?: true
  title?: true
  linkText?: true
  linkUrl?: true
  imageUrl?: true
  bgColor?: true
  isActive?: true
}

export type TrendingPromoCountAggregateInputType = {
  id?: true
  title?: true
  linkText?: true
  linkUrl?: true
  imageUrl?: true
  bgColor?: true
  isActive?: true
  _all?: true
}

export type TrendingPromoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TrendingPromo to aggregate.
   */
  where?: Prisma.TrendingPromoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TrendingPromos to fetch.
   */
  orderBy?: Prisma.TrendingPromoOrderByWithRelationInput | Prisma.TrendingPromoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TrendingPromoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TrendingPromos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TrendingPromos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TrendingPromos
  **/
  _count?: true | TrendingPromoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TrendingPromoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TrendingPromoMaxAggregateInputType
}

export type GetTrendingPromoAggregateType<T extends TrendingPromoAggregateArgs> = {
      [P in keyof T & keyof AggregateTrendingPromo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTrendingPromo[P]>
    : Prisma.GetScalarType<T[P], AggregateTrendingPromo[P]>
}




export type TrendingPromoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TrendingPromoWhereInput
  orderBy?: Prisma.TrendingPromoOrderByWithAggregationInput | Prisma.TrendingPromoOrderByWithAggregationInput[]
  by: Prisma.TrendingPromoScalarFieldEnum[] | Prisma.TrendingPromoScalarFieldEnum
  having?: Prisma.TrendingPromoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TrendingPromoCountAggregateInputType | true
  _min?: TrendingPromoMinAggregateInputType
  _max?: TrendingPromoMaxAggregateInputType
}

export type TrendingPromoGroupByOutputType = {
  id: string
  title: string
  linkText: string
  linkUrl: string
  imageUrl: string
  bgColor: string
  isActive: boolean
  _count: TrendingPromoCountAggregateOutputType | null
  _min: TrendingPromoMinAggregateOutputType | null
  _max: TrendingPromoMaxAggregateOutputType | null
}

type GetTrendingPromoGroupByPayload<T extends TrendingPromoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TrendingPromoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TrendingPromoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TrendingPromoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TrendingPromoGroupByOutputType[P]>
      }
    >
  >



export type TrendingPromoWhereInput = {
  AND?: Prisma.TrendingPromoWhereInput | Prisma.TrendingPromoWhereInput[]
  OR?: Prisma.TrendingPromoWhereInput[]
  NOT?: Prisma.TrendingPromoWhereInput | Prisma.TrendingPromoWhereInput[]
  id?: Prisma.StringFilter<"TrendingPromo"> | string
  title?: Prisma.StringFilter<"TrendingPromo"> | string
  linkText?: Prisma.StringFilter<"TrendingPromo"> | string
  linkUrl?: Prisma.StringFilter<"TrendingPromo"> | string
  imageUrl?: Prisma.StringFilter<"TrendingPromo"> | string
  bgColor?: Prisma.StringFilter<"TrendingPromo"> | string
  isActive?: Prisma.BoolFilter<"TrendingPromo"> | boolean
}

export type TrendingPromoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  linkText?: Prisma.SortOrder
  linkUrl?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  bgColor?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}

export type TrendingPromoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TrendingPromoWhereInput | Prisma.TrendingPromoWhereInput[]
  OR?: Prisma.TrendingPromoWhereInput[]
  NOT?: Prisma.TrendingPromoWhereInput | Prisma.TrendingPromoWhereInput[]
  title?: Prisma.StringFilter<"TrendingPromo"> | string
  linkText?: Prisma.StringFilter<"TrendingPromo"> | string
  linkUrl?: Prisma.StringFilter<"TrendingPromo"> | string
  imageUrl?: Prisma.StringFilter<"TrendingPromo"> | string
  bgColor?: Prisma.StringFilter<"TrendingPromo"> | string
  isActive?: Prisma.BoolFilter<"TrendingPromo"> | boolean
}, "id">

export type TrendingPromoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  linkText?: Prisma.SortOrder
  linkUrl?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  bgColor?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  _count?: Prisma.TrendingPromoCountOrderByAggregateInput
  _max?: Prisma.TrendingPromoMaxOrderByAggregateInput
  _min?: Prisma.TrendingPromoMinOrderByAggregateInput
}

export type TrendingPromoScalarWhereWithAggregatesInput = {
  AND?: Prisma.TrendingPromoScalarWhereWithAggregatesInput | Prisma.TrendingPromoScalarWhereWithAggregatesInput[]
  OR?: Prisma.TrendingPromoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TrendingPromoScalarWhereWithAggregatesInput | Prisma.TrendingPromoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TrendingPromo"> | string
  title?: Prisma.StringWithAggregatesFilter<"TrendingPromo"> | string
  linkText?: Prisma.StringWithAggregatesFilter<"TrendingPromo"> | string
  linkUrl?: Prisma.StringWithAggregatesFilter<"TrendingPromo"> | string
  imageUrl?: Prisma.StringWithAggregatesFilter<"TrendingPromo"> | string
  bgColor?: Prisma.StringWithAggregatesFilter<"TrendingPromo"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"TrendingPromo"> | boolean
}

export type TrendingPromoCreateInput = {
  id?: string
  title: string
  linkText: string
  linkUrl: string
  imageUrl: string
  bgColor: string
  isActive?: boolean
}

export type TrendingPromoUncheckedCreateInput = {
  id?: string
  title: string
  linkText: string
  linkUrl: string
  imageUrl: string
  bgColor: string
  isActive?: boolean
}

export type TrendingPromoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  linkText?: Prisma.StringFieldUpdateOperationsInput | string
  linkUrl?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  bgColor?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type TrendingPromoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  linkText?: Prisma.StringFieldUpdateOperationsInput | string
  linkUrl?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  bgColor?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type TrendingPromoCreateManyInput = {
  id?: string
  title: string
  linkText: string
  linkUrl: string
  imageUrl: string
  bgColor: string
  isActive?: boolean
}

export type TrendingPromoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  linkText?: Prisma.StringFieldUpdateOperationsInput | string
  linkUrl?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  bgColor?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type TrendingPromoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  linkText?: Prisma.StringFieldUpdateOperationsInput | string
  linkUrl?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  bgColor?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type TrendingPromoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  linkText?: Prisma.SortOrder
  linkUrl?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  bgColor?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}

export type TrendingPromoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  linkText?: Prisma.SortOrder
  linkUrl?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  bgColor?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}

export type TrendingPromoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  linkText?: Prisma.SortOrder
  linkUrl?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  bgColor?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}



export type TrendingPromoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  linkText?: boolean
  linkUrl?: boolean
  imageUrl?: boolean
  bgColor?: boolean
  isActive?: boolean
}, ExtArgs["result"]["trendingPromo"]>

export type TrendingPromoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  linkText?: boolean
  linkUrl?: boolean
  imageUrl?: boolean
  bgColor?: boolean
  isActive?: boolean
}, ExtArgs["result"]["trendingPromo"]>

export type TrendingPromoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  linkText?: boolean
  linkUrl?: boolean
  imageUrl?: boolean
  bgColor?: boolean
  isActive?: boolean
}, ExtArgs["result"]["trendingPromo"]>

export type TrendingPromoSelectScalar = {
  id?: boolean
  title?: boolean
  linkText?: boolean
  linkUrl?: boolean
  imageUrl?: boolean
  bgColor?: boolean
  isActive?: boolean
}

export type TrendingPromoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "linkText" | "linkUrl" | "imageUrl" | "bgColor" | "isActive", ExtArgs["result"]["trendingPromo"]>

export type $TrendingPromoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TrendingPromo"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    linkText: string
    linkUrl: string
    imageUrl: string
    bgColor: string
    isActive: boolean
  }, ExtArgs["result"]["trendingPromo"]>
  composites: {}
}

export type TrendingPromoGetPayload<S extends boolean | null | undefined | TrendingPromoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TrendingPromoPayload, S>

export type TrendingPromoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TrendingPromoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TrendingPromoCountAggregateInputType | true
  }

export interface TrendingPromoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TrendingPromo'], meta: { name: 'TrendingPromo' } }
  /**
   * Find zero or one TrendingPromo that matches the filter.
   * @param {TrendingPromoFindUniqueArgs} args - Arguments to find a TrendingPromo
   * @example
   * // Get one TrendingPromo
   * const trendingPromo = await prisma.trendingPromo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TrendingPromoFindUniqueArgs>(args: Prisma.SelectSubset<T, TrendingPromoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TrendingPromoClient<runtime.Types.Result.GetResult<Prisma.$TrendingPromoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TrendingPromo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TrendingPromoFindUniqueOrThrowArgs} args - Arguments to find a TrendingPromo
   * @example
   * // Get one TrendingPromo
   * const trendingPromo = await prisma.trendingPromo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TrendingPromoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TrendingPromoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TrendingPromoClient<runtime.Types.Result.GetResult<Prisma.$TrendingPromoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TrendingPromo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrendingPromoFindFirstArgs} args - Arguments to find a TrendingPromo
   * @example
   * // Get one TrendingPromo
   * const trendingPromo = await prisma.trendingPromo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TrendingPromoFindFirstArgs>(args?: Prisma.SelectSubset<T, TrendingPromoFindFirstArgs<ExtArgs>>): Prisma.Prisma__TrendingPromoClient<runtime.Types.Result.GetResult<Prisma.$TrendingPromoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TrendingPromo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrendingPromoFindFirstOrThrowArgs} args - Arguments to find a TrendingPromo
   * @example
   * // Get one TrendingPromo
   * const trendingPromo = await prisma.trendingPromo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TrendingPromoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TrendingPromoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TrendingPromoClient<runtime.Types.Result.GetResult<Prisma.$TrendingPromoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TrendingPromos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrendingPromoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TrendingPromos
   * const trendingPromos = await prisma.trendingPromo.findMany()
   * 
   * // Get first 10 TrendingPromos
   * const trendingPromos = await prisma.trendingPromo.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const trendingPromoWithIdOnly = await prisma.trendingPromo.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TrendingPromoFindManyArgs>(args?: Prisma.SelectSubset<T, TrendingPromoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TrendingPromoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TrendingPromo.
   * @param {TrendingPromoCreateArgs} args - Arguments to create a TrendingPromo.
   * @example
   * // Create one TrendingPromo
   * const TrendingPromo = await prisma.trendingPromo.create({
   *   data: {
   *     // ... data to create a TrendingPromo
   *   }
   * })
   * 
   */
  create<T extends TrendingPromoCreateArgs>(args: Prisma.SelectSubset<T, TrendingPromoCreateArgs<ExtArgs>>): Prisma.Prisma__TrendingPromoClient<runtime.Types.Result.GetResult<Prisma.$TrendingPromoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TrendingPromos.
   * @param {TrendingPromoCreateManyArgs} args - Arguments to create many TrendingPromos.
   * @example
   * // Create many TrendingPromos
   * const trendingPromo = await prisma.trendingPromo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TrendingPromoCreateManyArgs>(args?: Prisma.SelectSubset<T, TrendingPromoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TrendingPromos and returns the data saved in the database.
   * @param {TrendingPromoCreateManyAndReturnArgs} args - Arguments to create many TrendingPromos.
   * @example
   * // Create many TrendingPromos
   * const trendingPromo = await prisma.trendingPromo.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TrendingPromos and only return the `id`
   * const trendingPromoWithIdOnly = await prisma.trendingPromo.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TrendingPromoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TrendingPromoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TrendingPromoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TrendingPromo.
   * @param {TrendingPromoDeleteArgs} args - Arguments to delete one TrendingPromo.
   * @example
   * // Delete one TrendingPromo
   * const TrendingPromo = await prisma.trendingPromo.delete({
   *   where: {
   *     // ... filter to delete one TrendingPromo
   *   }
   * })
   * 
   */
  delete<T extends TrendingPromoDeleteArgs>(args: Prisma.SelectSubset<T, TrendingPromoDeleteArgs<ExtArgs>>): Prisma.Prisma__TrendingPromoClient<runtime.Types.Result.GetResult<Prisma.$TrendingPromoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TrendingPromo.
   * @param {TrendingPromoUpdateArgs} args - Arguments to update one TrendingPromo.
   * @example
   * // Update one TrendingPromo
   * const trendingPromo = await prisma.trendingPromo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TrendingPromoUpdateArgs>(args: Prisma.SelectSubset<T, TrendingPromoUpdateArgs<ExtArgs>>): Prisma.Prisma__TrendingPromoClient<runtime.Types.Result.GetResult<Prisma.$TrendingPromoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TrendingPromos.
   * @param {TrendingPromoDeleteManyArgs} args - Arguments to filter TrendingPromos to delete.
   * @example
   * // Delete a few TrendingPromos
   * const { count } = await prisma.trendingPromo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TrendingPromoDeleteManyArgs>(args?: Prisma.SelectSubset<T, TrendingPromoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TrendingPromos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrendingPromoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TrendingPromos
   * const trendingPromo = await prisma.trendingPromo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TrendingPromoUpdateManyArgs>(args: Prisma.SelectSubset<T, TrendingPromoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TrendingPromos and returns the data updated in the database.
   * @param {TrendingPromoUpdateManyAndReturnArgs} args - Arguments to update many TrendingPromos.
   * @example
   * // Update many TrendingPromos
   * const trendingPromo = await prisma.trendingPromo.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TrendingPromos and only return the `id`
   * const trendingPromoWithIdOnly = await prisma.trendingPromo.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TrendingPromoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TrendingPromoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TrendingPromoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TrendingPromo.
   * @param {TrendingPromoUpsertArgs} args - Arguments to update or create a TrendingPromo.
   * @example
   * // Update or create a TrendingPromo
   * const trendingPromo = await prisma.trendingPromo.upsert({
   *   create: {
   *     // ... data to create a TrendingPromo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TrendingPromo we want to update
   *   }
   * })
   */
  upsert<T extends TrendingPromoUpsertArgs>(args: Prisma.SelectSubset<T, TrendingPromoUpsertArgs<ExtArgs>>): Prisma.Prisma__TrendingPromoClient<runtime.Types.Result.GetResult<Prisma.$TrendingPromoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TrendingPromos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrendingPromoCountArgs} args - Arguments to filter TrendingPromos to count.
   * @example
   * // Count the number of TrendingPromos
   * const count = await prisma.trendingPromo.count({
   *   where: {
   *     // ... the filter for the TrendingPromos we want to count
   *   }
   * })
  **/
  count<T extends TrendingPromoCountArgs>(
    args?: Prisma.Subset<T, TrendingPromoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TrendingPromoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TrendingPromo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrendingPromoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TrendingPromoAggregateArgs>(args: Prisma.Subset<T, TrendingPromoAggregateArgs>): Prisma.PrismaPromise<GetTrendingPromoAggregateType<T>>

  /**
   * Group by TrendingPromo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrendingPromoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TrendingPromoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TrendingPromoGroupByArgs['orderBy'] }
      : { orderBy?: TrendingPromoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TrendingPromoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTrendingPromoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TrendingPromo model
 */
readonly fields: TrendingPromoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TrendingPromo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TrendingPromoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TrendingPromo model
 */
export interface TrendingPromoFieldRefs {
  readonly id: Prisma.FieldRef<"TrendingPromo", 'String'>
  readonly title: Prisma.FieldRef<"TrendingPromo", 'String'>
  readonly linkText: Prisma.FieldRef<"TrendingPromo", 'String'>
  readonly linkUrl: Prisma.FieldRef<"TrendingPromo", 'String'>
  readonly imageUrl: Prisma.FieldRef<"TrendingPromo", 'String'>
  readonly bgColor: Prisma.FieldRef<"TrendingPromo", 'String'>
  readonly isActive: Prisma.FieldRef<"TrendingPromo", 'Boolean'>
}
    

// Custom InputTypes
/**
 * TrendingPromo findUnique
 */
export type TrendingPromoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrendingPromo
   */
  select?: Prisma.TrendingPromoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrendingPromo
   */
  omit?: Prisma.TrendingPromoOmit<ExtArgs> | null
  /**
   * Filter, which TrendingPromo to fetch.
   */
  where: Prisma.TrendingPromoWhereUniqueInput
}

/**
 * TrendingPromo findUniqueOrThrow
 */
export type TrendingPromoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrendingPromo
   */
  select?: Prisma.TrendingPromoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrendingPromo
   */
  omit?: Prisma.TrendingPromoOmit<ExtArgs> | null
  /**
   * Filter, which TrendingPromo to fetch.
   */
  where: Prisma.TrendingPromoWhereUniqueInput
}

/**
 * TrendingPromo findFirst
 */
export type TrendingPromoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrendingPromo
   */
  select?: Prisma.TrendingPromoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrendingPromo
   */
  omit?: Prisma.TrendingPromoOmit<ExtArgs> | null
  /**
   * Filter, which TrendingPromo to fetch.
   */
  where?: Prisma.TrendingPromoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TrendingPromos to fetch.
   */
  orderBy?: Prisma.TrendingPromoOrderByWithRelationInput | Prisma.TrendingPromoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TrendingPromos.
   */
  cursor?: Prisma.TrendingPromoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TrendingPromos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TrendingPromos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TrendingPromos.
   */
  distinct?: Prisma.TrendingPromoScalarFieldEnum | Prisma.TrendingPromoScalarFieldEnum[]
}

/**
 * TrendingPromo findFirstOrThrow
 */
export type TrendingPromoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrendingPromo
   */
  select?: Prisma.TrendingPromoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrendingPromo
   */
  omit?: Prisma.TrendingPromoOmit<ExtArgs> | null
  /**
   * Filter, which TrendingPromo to fetch.
   */
  where?: Prisma.TrendingPromoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TrendingPromos to fetch.
   */
  orderBy?: Prisma.TrendingPromoOrderByWithRelationInput | Prisma.TrendingPromoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TrendingPromos.
   */
  cursor?: Prisma.TrendingPromoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TrendingPromos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TrendingPromos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TrendingPromos.
   */
  distinct?: Prisma.TrendingPromoScalarFieldEnum | Prisma.TrendingPromoScalarFieldEnum[]
}

/**
 * TrendingPromo findMany
 */
export type TrendingPromoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrendingPromo
   */
  select?: Prisma.TrendingPromoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrendingPromo
   */
  omit?: Prisma.TrendingPromoOmit<ExtArgs> | null
  /**
   * Filter, which TrendingPromos to fetch.
   */
  where?: Prisma.TrendingPromoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TrendingPromos to fetch.
   */
  orderBy?: Prisma.TrendingPromoOrderByWithRelationInput | Prisma.TrendingPromoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TrendingPromos.
   */
  cursor?: Prisma.TrendingPromoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TrendingPromos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TrendingPromos.
   */
  skip?: number
  distinct?: Prisma.TrendingPromoScalarFieldEnum | Prisma.TrendingPromoScalarFieldEnum[]
}

/**
 * TrendingPromo create
 */
export type TrendingPromoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrendingPromo
   */
  select?: Prisma.TrendingPromoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrendingPromo
   */
  omit?: Prisma.TrendingPromoOmit<ExtArgs> | null
  /**
   * The data needed to create a TrendingPromo.
   */
  data: Prisma.XOR<Prisma.TrendingPromoCreateInput, Prisma.TrendingPromoUncheckedCreateInput>
}

/**
 * TrendingPromo createMany
 */
export type TrendingPromoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TrendingPromos.
   */
  data: Prisma.TrendingPromoCreateManyInput | Prisma.TrendingPromoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TrendingPromo createManyAndReturn
 */
export type TrendingPromoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrendingPromo
   */
  select?: Prisma.TrendingPromoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TrendingPromo
   */
  omit?: Prisma.TrendingPromoOmit<ExtArgs> | null
  /**
   * The data used to create many TrendingPromos.
   */
  data: Prisma.TrendingPromoCreateManyInput | Prisma.TrendingPromoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TrendingPromo update
 */
export type TrendingPromoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrendingPromo
   */
  select?: Prisma.TrendingPromoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrendingPromo
   */
  omit?: Prisma.TrendingPromoOmit<ExtArgs> | null
  /**
   * The data needed to update a TrendingPromo.
   */
  data: Prisma.XOR<Prisma.TrendingPromoUpdateInput, Prisma.TrendingPromoUncheckedUpdateInput>
  /**
   * Choose, which TrendingPromo to update.
   */
  where: Prisma.TrendingPromoWhereUniqueInput
}

/**
 * TrendingPromo updateMany
 */
export type TrendingPromoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TrendingPromos.
   */
  data: Prisma.XOR<Prisma.TrendingPromoUpdateManyMutationInput, Prisma.TrendingPromoUncheckedUpdateManyInput>
  /**
   * Filter which TrendingPromos to update
   */
  where?: Prisma.TrendingPromoWhereInput
  /**
   * Limit how many TrendingPromos to update.
   */
  limit?: number
}

/**
 * TrendingPromo updateManyAndReturn
 */
export type TrendingPromoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrendingPromo
   */
  select?: Prisma.TrendingPromoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TrendingPromo
   */
  omit?: Prisma.TrendingPromoOmit<ExtArgs> | null
  /**
   * The data used to update TrendingPromos.
   */
  data: Prisma.XOR<Prisma.TrendingPromoUpdateManyMutationInput, Prisma.TrendingPromoUncheckedUpdateManyInput>
  /**
   * Filter which TrendingPromos to update
   */
  where?: Prisma.TrendingPromoWhereInput
  /**
   * Limit how many TrendingPromos to update.
   */
  limit?: number
}

/**
 * TrendingPromo upsert
 */
export type TrendingPromoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrendingPromo
   */
  select?: Prisma.TrendingPromoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrendingPromo
   */
  omit?: Prisma.TrendingPromoOmit<ExtArgs> | null
  /**
   * The filter to search for the TrendingPromo to update in case it exists.
   */
  where: Prisma.TrendingPromoWhereUniqueInput
  /**
   * In case the TrendingPromo found by the `where` argument doesn't exist, create a new TrendingPromo with this data.
   */
  create: Prisma.XOR<Prisma.TrendingPromoCreateInput, Prisma.TrendingPromoUncheckedCreateInput>
  /**
   * In case the TrendingPromo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TrendingPromoUpdateInput, Prisma.TrendingPromoUncheckedUpdateInput>
}

/**
 * TrendingPromo delete
 */
export type TrendingPromoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrendingPromo
   */
  select?: Prisma.TrendingPromoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrendingPromo
   */
  omit?: Prisma.TrendingPromoOmit<ExtArgs> | null
  /**
   * Filter which TrendingPromo to delete.
   */
  where: Prisma.TrendingPromoWhereUniqueInput
}

/**
 * TrendingPromo deleteMany
 */
export type TrendingPromoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TrendingPromos to delete
   */
  where?: Prisma.TrendingPromoWhereInput
  /**
   * Limit how many TrendingPromos to delete.
   */
  limit?: number
}

/**
 * TrendingPromo without action
 */
export type TrendingPromoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrendingPromo
   */
  select?: Prisma.TrendingPromoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrendingPromo
   */
  omit?: Prisma.TrendingPromoOmit<ExtArgs> | null
}
